CONTRIBUTING.md
README.md

Without this, users will have a more challenging time contributing to
vanagon.

(CPR-232) Add CONTRIBUTING.md to vanagon

---

vanagon.gemspec

Having a license in the gemspec is a good practice, and gem will warn
when building if a dependency has no version requirements, so this
commit adds the license field and adds a versioning requirement to the
yard development dependency.

(maint) Add license, update yard dependency in gemspec

---

templates/Makefile.erb

Previously, a build_requires step would only cause the final, top-level
target of the dependent to have a dependency. This means that it's
possible for the entire dependent to be built before the dependency,
entirely defeating the purpose of build dependencies.
Now, the dependent-configure target depends on the dependency target,
which ensures that include directories, etc will be properly found
when the dependent is configured.

(maint) Finish build deps before configuring dependents

---

lib/vanagon/platform/dsl.rb

When using `yum_repo` only attempt to install curl if the package is not already present.  The following failure was seen on platforms that do not have any yum repos configured by default.
```
There are no enabled repos.
Run "yum repolist all" to see the repos you have.
You can enable repos with yum-config-manager --enable <repo>
```

(maint) yum_repo - only install curl if missing

---

lib/vanagon/platform/osx.rb
templates/osx/preinstall.erb

Starting with OSX 10.11, /usr is protected by default.  This commit
updates the location of the bill-of-materials to use the docdir in
/usr/local.
If we're in an upgrade, the preinstall script removes the old
bill-of-materials in /usr if it exists.

(RE-5758) Move Vanagon bill-of-materials location on OSX

---

lib/vanagon/component/dsl.rb
spec/lib/vanagon/component/dsl_spec.rb

Previously, when reading in the puppet and mcollective service
scripts to create their subsystems on AIX, a newline in the string
was causing the command and its arguments to appear on separate lines.
This caused `mksys` to not set signorm and sigforce, rendering
the service unstoppable.
We now chomp the newline to ensure the arguments are included with
the service command.

(CPR-240) Ensure AIX doesn't include newlines when creating puppet subsystem

---

templates/solaris/11/p5m.erb

Previously the ips manifest made the naive assumption that all services
could live at /var/svc/manifest or /lib/svc/manifest. Solaris 11 won't
detect services when there, and unfortunately, when moving the services
into subdirs of those directories, the manifest did not previously drop
the subdirectory from the package. This commit updates the manifest to
drop all of the directories holding smf definitions and also to restart
the manifest-import service for each service.

(CPR-242) Don't assume all smf services are top level

---

README.md

When viewed from github, the README.md links resolve correctly, but when
viewed in generated docs, they do not. This commit fully qualifies the
links so that they work in both cases.

(maint) Update links in README.md to point to github

---

.travis.yml

Setting sudo to false will allow travis to use container and ideally
produce a faster build.

(maint) Update travis config to set sudo to false

---

lib/vanagon/platform.rb

Currently the arguments passed to useradd vs usermod are
backwards. This swaps the arguments so the correct set
is passed to the usermod/useradd commands.

(maint) Fix user management arguments

---

lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb
spec/lib/vanagon/platform/dsl_spec.rb

NXOS was long ago renamed to cisco-wrlinux, so this commit goes through
and removes the nxos specific methods, tests and logic. All repos that
were exercising nxos platforms have been updated to remove that usage.

(maint) Remove nxos platform from vanagon

---

templates/deb/control.erb

Currently, we define the description for a project in that projects
file, then parse it out into the debian control file. This is all fine
and dandy for one-line descriptions, but when you add in multi-line
descriptions, it gets interesting. Most multi-line descriptions will
already have line breaks in them, for ease of reading and writing for
the maintainer. The way things currently are, we are adding in an
additional line break for every line we add in to the control file.
Debian doesn't know how to parse descriptions with all of these line
breaks, and fails to build the package. This commit removes the line
break addition.

(maint) Do not add additional line breaks to description 

---

lib/vanagon/component/dsl.rb
templates/deb/rules.erb
templates/rpm/project.spec.erb

Previously links were not added to the files list which meant that they
would not be collected if they fell outside of the directories being
watched by vanagon. This commit adds them to the files list.
The cp calls in the spec and rules files need the -R flag added to
ensure that links are not dereferenced and are copied as is, which would
otherwise break packaging.

(CPR-248) Add link to files list in link DSL method

---

templates/Makefile.erb

Previously the file-list-before-build could happen after the base
directories were created, which had the side effect of making it appear
as though those directories were not created by the current project.
This commit addresses that issue by ensuring that the
file-list-before-build is generated before any directories, and as early
as possibly in the Makefile.

(CPR-250) Ensure directories are created after initial file list

---

templates/solaris/11/p5m.erb

On solaris 11, /var/run is a symlink to /system/volatile, which results
in file conflicts when attempting to install a package which declares a
directory under /var/run. This commit addresses that by rewriting the
directory entries under /var/run to move them under /system/volatile
instead. /system/volatile must then be itself dropped to avoid conflicts
on package install.

(CPR-251) Move /var/run/* to /system/volatile on solaris 11

---

lib/vanagon/platform/osx.rb
lib/vanagon/platform/solaris_10.rb
lib/vanagon/project.rb
lib/vanagon/project/dsl.rb
templates/Makefile.erb
templates/deb/docs.erb
templates/rpm/project.spec.erb
templates/solaris/11/p5m.erb

Previously, the bill-of-materials was laid down by default in the docdir
on various platforms. This causes problems on platforms like newer osx,
and isn't very configurable, so this commit adds a method to the project
DSL which allows the location to be overridden. This is a backward
compatible addition, and contains some shims that can be removed when
bill-of-materials is no longer desired to be on by default.

(CPR-247) Add BOM method to project DSL

---

vanagon.gemspec

Because of the use of keyword arguments with defaults, vanagon won't
work on anything less than ruby 2.1.0, so this commit updates the
gemspec to reflect that. We also add the specification version to
enforce a relatively modern version of rubygems.

(maint) Add minimum ruby version and specification to gemspec

---

vanagon.gemspec

Previously, Vanagon's minimum Ruby version was set to '~> 2.1.0',
which meant that versions equal or greater than 2.1.0 but less than
2.2.0 were allowed. Any version of Ruby above 2.1.0 in the 2.x series
should be valid.

(maint) Fix minimum Ruby version to allow Ruby 2.x

---

CHANGELOG.md
lib/vanagon/platform/solaris_11.rb

On Solaris 11, the version transformation to an IPS-compatible
format (minus alpha characters) also makes it into the VERSION
file.
This updates the logic to operate on a duplicate object instead
of the actual version variable when making the transformation,
so that the transformed value only winds up where we explicitly
ask for it.

(RE-5979) Solaris-11 VERSION file should match other platforms

---

lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb
lib/vanagon/platform/windows.rb
templates/Makefile.erb
templates/windows/chocolateyInstall.ps1.erb
templates/windows/chocolateyUninstall.ps1.erb
templates/windows/project.nuspec.erb

These are changes needed to build nuget packages. Once https://github.com/puppetlabs/vanagon/pull/217 is sorted out, we can use the procedure established there to build either msi or nuget packages. That will likely require that the methods added here to windows.rb will have to be moved.

(RE-5680) Teach vanagon how to build nuget archives on windows

---

lib/vanagon/component.rb
templates/Makefile.erb

On windows, we need to be able to set certain environment variables
prior to unpacking our source. The is mainly for dealing with sticky
things like symlinks in cygwin versus windows environments. However,
this only works when we actually have something to unpack. Otherwise,
our extract command returns an empty string. In order for the makefile
not to fail, we return a simple ':' when there is nothing to extract.

(maint) Allow environment to be specified when unpacking tarballs

---

lib/vanagon/component.rb
lib/vanagon/component/dsl.rb
spec/lib/vanagon/component/dsl_spec.rb
spec/lib/vanagon/component_spec.rb
templates/Makefile.erb

Tools like cmake use out of tree builds to prevent source files and
build files from intermingling; when they're used all commands are run
from a separate build directory. This commit adds a #build_dir method to
the component (and DSL) that when set will create the build dir relative
to the source directory for each component, and when running any build
command will cd into the build directory before running the command.

Add helper for out of tree builds

---

lib/vanagon/component.rb
lib/vanagon/component/source/http.rb

Because of excitement on windows, we need to set certain environment
variables when we unpack tarballs that contain symlinks. That means
we've modified the Makefile to include the environment settings as well
as '&& \'. When this is followed by an empty line, make fails. So, in
order to prevent this failure, we need to pass in ':' so that nothing
happens when there is no extract command to pass in.

(maint) Pass ':' if there is nothing to extract

---

lib/vanagon/platform/windows.rb
templates/windows/project.nuspec.erb

Nuget is challenging when it comes to versions. We can only have four
numeric elements seperated by periods. We have the option of specifying
a build version, but this must be the last element in the version tag
and must be a dash followed immediately by a letter and then either
numbers or letters but no punctuation. Since we cannot guarentee a git
short sha will begin with a letter, this isn't an options.
As a result, we must have a version of at most four elements containing
only numbers. If we only have three elements in the version string, then
we get to use the release variable. Otherwise, we just just the first
four elements from the version.
Gross.

(maint) Handle git versioning scheme in nuspec template

---

templates/windows/chocolateyUninstall.ps1.erb

We should still succeed at uninstall if files are missing.

(maint) Skip deleting missing files

---

bin/build
lib/vanagon/component.rb
lib/vanagon/component/dsl.rb
lib/vanagon/driver.rb
lib/vanagon/optparse.rb
spec/lib/vanagon/component/dsl_spec.rb
spec/lib/vanagon/optparse_spec.rb
templates/Makefile.erb

This pull request adds a `check` stage to components for running component unit tests/code linting/static analysis after compilation and before installation/packaging. It also adds a `--skipcheck` flag to the `build` executable to disable the `check` stage on all components when build speed is more important than code verification.

(RE-3979) Add `check` stage to components

---

lib/vanagon/component/dsl.rb
spec/lib/vanagon/component/dsl_spec.rb
templates/Makefile.erb

We need to be able to add patches to some of the gems we're providing in
our windows build. This commits adds in a new gem-patch task to the
Makefile if we have gems. It also exposes the extension type for the
source that we're currently working with. In the special case we're
dealing with no source or a git repo, we have to manually specify the
extension type. There's probably a better way to do this....

(CPR-263) Teach vanagon how to add post-installation gem patches

---

lib/vanagon/component/source/http.rb

Prior to this patch, vanagon could not work with a zip file as a source
to fetch/extract and build a package from. This simply adds zip to the
ARCHIVE_EXTENSIONS constant and returns the correct command to use for
unpacking the archive.

(CPR-266) Allow vanagon to work with zip files

---

lib/vanagon/component/source/http.rb

Prior to this PR, if we had a package that ended with `.tar.gz`, we
would be unable to unpack it. This method would return the wrong thing.
We need the leading `.` in this string in order to correctly match this
ending.

(maint) Fix type in extract

---

lib/vanagon/component/source/http.rb

This PR updates a typo made when defining what extension we are dealing
with. Rather then `||`, ruby case requires `,` to define multiple
possibilities for satisfying when we enter this block.

(maint) Fix case typo

---

lib/vanagon/component/source/http.rb

In order to facilitate config files for vim, this commit
adds the .vim extension to the list of NON_ARCHIVE_EXTENSIONS
in the component/source/http.rb file

(PA-121) adding support for .vim syntax files

---

lib/vanagon/component/source/http.rb

JSON files should be able to be used as non archive sources, since it's
fairly common to have them as configuration.

(maint) Allow json files to be used as sources

---

lib/vanagon/component/dsl.rb
lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb
lib/vanagon/platform/windows.rb
spec/lib/vanagon/component/dsl_spec.rb

This PR also sets `@install` for windows and fixes a typo

(maint) Allow Vanagon to override `cp`

---

lib/vanagon/common/pathname.rb

We are currently using `expand_path` to normalize any path references in
whichever vanagon project we are building. This helps us handle any
extra `/` or `..` in the path. Unfortunately, this method doesn't work
well with paths that are not in unix format and do not exist on the
current machine. Since we are moving to add support for using vangon to
build windows projects, we need to handle windows paths. If we try to
run `expand_path` on an MS-DOS style path (i.e., `C:/Program
Files/Puppet Labs/Puppet`), then `expand_path`, in it's attempt to
normalize the path, will prepend the current working directory to the
path. This is the directory where you kick off your vanagon build. For
me, this would result in paths like
`/home/melissa/puppet-agent/C:/Program Files/Puppet Labs/Puppet`. These …

(maint) Use pathname to normalize paths 

---

lib/vanagon/project.rb
templates/Makefile.erb

On windows, we need the ability to deal with spaces in path names. This
commit does two things to handle that. First, it adds double quotes
around all the path names when we query the filesystem. Then, it adds
cygpath to normalize the path. This lets us change Progra~1 to Program
Files. Super gross, I know. I didn't know what else to do. There are
enough assumptions on cygwin currently, I figured it was safe to add one
more.

(maint) Normalize path shortcuts

---

lib/vanagon/component/source/http.rb
spec/lib/vanagon/component/source/http_spec.rb

Prior to this patch, we had to explicitly add every extension we wanted
to use a source with vanagon. This resulted in lots of small patches
with a simple addition of .json or .txt or something. It also meant
that to use those extensions, a release of vanagon was needed. This
slows down work.
Instead, we'll default to any extension that is not explicitly called
out as an archive, is simply a flat file and able to be used that way.
The net result here is that only new archive extensions will require
patches.

(CPR-269) Assume unknown extension types are just files

---

templates/windows/chocolateyInstall.ps1.erb
templates/windows/chocolateyUninstall.ps1.erb

Our current nuget packaging scripts make a few assumptions that have
turned out to be false. Namely, these assumptions surround the path
specifications for where we are installing. Previously, we were using a
list of files and directories picked up from the project and component
configs. This was fine, but we have a better source for this
information. We have a file-list.txt file that details all of the files
and directories (even if they are empty) that are to be included in the
package. These paths have already been normalized to deal with spaces
and shortcuts (if any are used). So any use of `Progra~1` will already
have been expanded to `Program Files`. This is especially important
because we cannot guarentee that `Progra~1` will expand to what we want
it to be on the system the …

(CPR-264) Rewrite chocolatey packaging scripts

---

templates/deb/rules.erb

Prior to this, dh_usrlocal ran and would cause package builds to fail if
things were placed in /usr/local. This patch simply declares an override
of the dh_userlocal target that is a noop.

(RE-6106) Allow for putting items in /usr/local on debian

---

templates/rpm/project.spec.erb

Some projects do not have directories for us to package, ie pl-build-tools.  This update excludes the file list in this case preventing errors and failure in RPM 4.13
Test against pl-build-tools (without dirs) and pl-build-tools-vanagon (with dirs)
Before
```
++ cat /var/tmp/tmp.13oP32Bje8/rpmbuild/SOURCES/file-list-for-rpm
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip /usr/bin/strip
+ /usr/lib/rpm/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Processing files: pl-build-tools-release-22.0.0-4.fedoraf23.noarch
RPM build errors:
error: Empty %files file /var/tmp/tmp.13oP32Bje8/rpmbuild/SOURCES/file-list-for-rpm …
```

(maint) RPM only set file-list-for-rpm path if project has directories

---

lib/vanagon/component.rb
lib/vanagon/component/dsl.rb
spec/lib/vanagon/component/dsl_spec.rb

Vanagon builds should be repeatable over the same temporary directory
(via make). Currently attempting to repeat a link fails the build
because the symlink already exists. Only attempt to create the symlink
if it doesn't already point to the correct file.

(CPR-273) Allow repeatable builds

---

lib/vanagon/component/source/git.rb
lib/vanagon/utilities.rb
spec/lib/vanagon/component/source/git_spec.rb

Vanagon should halt and raise an error if any of the
git commands fail. It does not currently, this will
add the functionality to fail and raise an error
if any of the git commands fail

(CPR-272) git submodule failure does not stop vanagon

---

lib/vanagon/driver.rb
lib/vanagon/engine/base.rb
lib/vanagon/engine/docker.rb
lib/vanagon/engine/hardware.rb
lib/vanagon/engine/local.rb
lib/vanagon/engine/pooler.rb

Prior to this, the hardware engine attempted to release the lock it had
on a system when regardless of the outcome of the vanagon build.
However, due to an if statement that could never evaluate to true, that
wasn't happening.
In debugging the problem, there was no way to figure out which engine
was being invoked. This commit adds a @name attribute to all engines so
other parts of the codebase can know what engine is being invoked.
This now means that if the hardware engine is being used, the ensure
block in driver.rb will release the lock regardless of pass/fail on the
build.

(maint) Hardware engine should release lock upon failure

---

README.md
lib/vanagon/utilities.rb
spec/lib/vanagon/utilities_spec.rb

This commit adds support for enabling SSH agent forwarding by checking
for the existence of an environment variable, VANAGON_SSH_AGENT.  If
set, Vanagon will construct the ssh command with the option to forward
the authentication agent connection.

(RE-6476) Add option to enable SSH agent forwarding

---

lib/vanagon/component/source/http.rb

On windows, we need to use 7za to unpack zip archives. We don't have
`unzip` available and `gunzip` throws an error. The only problem is we
don't have any guarantees 7za will be on the path. It is installed as a
part of chocolatey, but we need to set path in the component in order to
ensure we have access to it.

(maint) Allow zip archives to be unpacked with 7za

---

lib/vanagon/platform/windows.rb
resources/windows/wix/project.wxs.erb

This PR adds the main WiX file that will build MSIs for vanagon. It holds all generic logic to build a MSI as well as any best practices that we want to use.
This file will contain:
- Product and Package elements
- Top level Feature and Directory elements
- Any properties and custom actions for the Remembered Installation directory pattern
This supercedes #271, which holds the conversation for this work but not any of the work due to an error in pushing by the author. I was no longer confident it had a correct merge history from master and from vanaon_for_the_win branches.

(RE-6237) Main WiX project file

---

lib/vanagon/engine/local.rb
lib/vanagon/utilities.rb
spec/lib/vanagon/engine/local_spec.rb
spec/lib/vanagon/utilities_spec.rb
spec/spec_helper.rb

This PR replaces PR #284.
Builds currently fail when using the local engine, because `@remote_dir` is not defined. Additionally, `gem install` fails due to numerous `RUBY_` and `BUNDLER_` environment variables being set when running `bundle exec build`.
I worked with @pyther to bang his initial work into something solid, and wrote some spec tests to cover the initial scope of the work done. `Vanagon::Utilities#local_command` now runs in a clean, unbundled environment and the Local build engine produces usable builds. There's still room for improvement (test coverage is still not 100% on the new work) but this should be in sturdy, workable shape now.
Thanks to @MikaelSmith and @pyther for their work on the original PRs.

(CPR-293, CPR-294) Fix Local engine, unbundle local commands

---

lib/vanagon/component.rb
lib/vanagon/component/dsl.rb

We should have the ability to specify what license each of our
components has. Although not all of the packaging formats we support
will be able to present all the component licenses, some do. For those
that do, we should make this piece of information available.

(maint) Add license to components

---

resources/rpm/project.spec.erb

Currently, due to the way RPM scriptlet ordering works, on AIX
we are stopping the service *after* we restart the service on upgrades.
This makes a couple of changes.
First, make the service stop in the %preun conditional on package
uninstall, like the rest of the platforms.
Second, moves the upgrade %post actions to %postun, as that's more likely where
we actually want those to happen.
Unfortunately, neither change will help users who already have a version
of P-A installed, as the preun/postun scripts are run from the *previous*/
already installed package during upgrades, but this should fix the problem
going forward.

(PE-13450) AIX upgrade leaves services stopped

---

resources/windows/nuget/chocolateyInstall.ps1

Previously if the destination existed when trying to create an empty
directory, installation would fail. Now installation will skip creating
the directory if it already exists, but will still fail if a
non-directory exists at that path.

(CPR-290) Only create directory if path doesn't exist

---

lib/vanagon/platform/windows.rb
spec/fixtures/wix/resources/windows/wix/file-1.wxs
spec/fixtures/wix/resources/windows/wix/file-2.wxs
spec/fixtures/wix/resources/windows/wix/file-3.wxs.erb
spec/fixtures/wix/resources/windows/wix/file-4.wxs.erb
spec/fixtures/wix/resources/windows/wix/include/include-sample-1.wxs
spec/fixtures/wix/resources/windows/wix/project.filter.xslt.erb
spec/fixtures/wix/resources/windows/wix/project.wxs
spec/fixtures/wix/resources/windows/wix/ui/ui-sample-1.wxs
spec/lib/vanagon/platform/windows_spec.rb

As noted in discussion, this is now focussing in RE-6456, i.e. allowing Vanagon to include project specific files as well as a generic set of wix files.
/cc @melissa, @jpogran and @McdonaldSeanp

(RE-6456) Allow vanagon to pull in project specific files

---

README.md

The readme is vague in its description of what a recent version is. This commit
explicitly details the minimum version required of 2.1.x.  This is due to gem
dependencies.
Obsoletes #293

(MAINT) Specify ruby version

---

.gitignore

This commit updates the gitignore to be more inline with other Puppetlabs
projects e.g. ignoring .bundle and Gemfile.local
Obsoletes: #294

(MAINT) Update gitignore

---

lib/vanagon/component/dsl.rb
lib/vanagon/platform/windows.rb
resources/windows/wix/filter.xslt.erb

This updates the service file handling to for product specific wix
service file fragments. The service .exe still needs to be filtered out
from the harvest, so the list of service .exe's are placed in the filter
file.
The project.filter.xslt file has also been renamed to simply
filter.xslt.  This file is given a generic name as there may be a need
in the future to filter out other files from the harvest.
The nssm.exe file is not being correctly matched in the harvest - this
appears to be an issue with the build itself (the nssm and some other
files are not being dropped in the correct folder). This issue will be
checked, ticketed if necessary and handled in seperate PR.

(RE-6640) Filter out service files from harvest

---

lib/vanagon/platform/windows.rb
resources/windows/wix/project.wxs.erb

This commit updates the light commands to do the following:
* rename "staging" to SourceDir, since light looks specifically
for a directory called SourceDir
* remove the -dr flag from heat.exe, as we want all the defaults
from heat (as we will use these defaults in light.exe)
* add the -srd flag to heat.exe to ignore the source directory
because again, we want to use the defaults in light
* add the -b flag to light.exe to point it to where we are
putting SourceDir (which is in the temp folder)
* remove INSTALLDIR, we are no longer using it as its set in
the defaults.
* remove the componentgroup element from the project .wxs file
as this is created in heat already
* Update the registrykey element to use ForceCreateOnInstall
instead of action, as action is deprecated now
With all these …

(maint) update the WiX toolset

---

resources/windows/wix/project.wxs.erb

Custom Actions and sequences are to be put into the puppet-agent or
other product specific code areas.
This PR removes the Custom action sequences from the product file
completely. A PA side PR will be used to create the custom actions
there.

(RE-6464) Remove Custom Actions/Sequences from Generic Product file

---

resources/windows/wix/project.wxs.erb
resources/windows/wix/registryEntries.wxs.erb

This commit refactors project.wxs to remove a component
that was causing problems with the WiX build. The component
doesn't actually need to be removed, only moved outside
the "product" element and put inside a "ComponentGroupRef"
element in another WiX fragment.
Following this commit the WiX compiler will successfully
compile and the sanitary checks done by WiX at the end
of compilation will not fail out. Meaning Vanagon now
successfully completes.

(maint) Redo project.wxs

---

lib/vanagon/platform/windows.rb

The for; do; done loop that executes the candle command fails to trap
errors. Add a check that causes the loop to exit on failure if any of
the wix files fail compilation.

(MAINT) Ensure Candle command fails correctly

---

resources/windows/wix/filter.xslt.erb

This fixes an irritant in the ERB translation which leads to multiple
blank lines in the filter file. While not affecting functionality, it
represented an untidyness that "made me sad" in the PDX vernacular.
Although it looks like all lines have changed, in fact all that was done
was to run the :set fileformat=unix in vi.
And yes - I also removed an unneeded space.

(MAINT) Convert filter.wxs.erb file to Unix Mode

---

lib/vanagon/utilities.rb
spec/lib/vanagon/engine/hardware_spec.rb
spec/lib/vanagon/engine/local_spec.rb

The previous commit for CPR-293 left out some updates to the
`local_command` method that were required by `get_remote_workdir`.
Since the local engine doesn't do anything special to initialize
`remote_workdir`, and it's used when calling make to build the project
and in the local engine for `ship_workdir` and
`retrieve_built_artifact`, update `local_command` to handle the
`return_command_output` option.

(CPR-293) Fix local engine again

---

lib/vanagon/component/dsl.rb
resources/windows/wix/componentrefs.wxs.erb
resources/windows/wix/project.wxs.erb

The service component reference is generated from "service_name" using
the Wix rules, i.e. only legal characters are Alphanumeric and _.
This is used to generate a table of service references to ensure the
service components are loaded into the MSI.

(RE-6440) Add Service Component References

---

lib/vanagon/component/dsl.rb

This corrects a Typo that was spotted in PR #308
The service_file argument is incorrect.
Have also removed :name as this is no longer needed for either service
table or associated directory list creation (see #307)

(MAINT) Fix service_file for windows service def

---

lib/vanagon/platform/windows.rb
resources/windows/wix/directorylist.wxs.erb
spec/lib/vanagon/platform/windows_spec.rb

This commit will add functionality to use the existing
get_services functionality for a project to generate
a directorylist.wxs file that contains the wix structure
of directories containing binaries for the project.
Because more than one service can point to the same binary
the directorylist may contain more than one directory wix
element at the top of the directory tree. In WiX this is
fine as long as any elements that are supposed to point
to the same directory have different IDs and no "name"
attribute.

(RE-6455) Create directorylist.wxs

---

lib/vanagon/driver.rb
lib/vanagon/project.rb
spec/lib/vanagon/utilities_spec.rb

Currently, vanagon builds will occasionally fail on
what turn out to be transient, short-lived issues.
This wraps the main build in the retry method to try
to reduce the impact of transient infrastructure issues.
As set, will retry up to 3 times with a 1-hour timeout.

(RE-6551) Make vanagon builds retry on errors

---

resources/windows/wix/registryEntries.wxs.erb

These entries are being over-ridden by a more Puppet-Agent specific set
of registry entries for puppet-agent.
Rather than deleting this file, it is being left in place with comments
to give guidance on how to set registry entries.
This model will also be applied to the properties and other common
files.

(RE-6743) Vanagon generic registry entries

---

lib/vanagon/platform/deb.rb

This allows cross-compiled packages to use correct tools (such as the
target arch strip command) when generating the package. When noarch is
set, this becomes a no-op.

(RE-6520) Specify architecture when generating Debian packages

---

lib/vanagon/platform/windows.rb
resources/windows/wix/componentgroup.wxs.erb
resources/windows/wix/project.wxs.erb

Vanagon side changes to introduce UI files:
1. UI reference to ensure code is compiled into MSI
2. Fix to light.exe to all localisation reference.
This PR also includes [RE-6757](https://tickets.puppetlabs.com/browse/RE-6757) 
See Puppet Agent PR [#568](https://github.com/puppetlabs/puppet-agent/pull/568)

(RE-6849) UI/Localisation Vanagon side updates

---

resources/osx/postinstall.erb
resources/osx/preinstall.erb

Currently, osx will only load services if the pkgutil check
detects a previous package installed. I think this is failing
because, in the postinstall, the package is no longer installed.
This changes the postinstall to unconditionally load services
on OSX.
Also fixes a whitespace typo in the preinstall script

(RE-6739) Load services unconditionally on osx

---

resources/osx/postinstall.erb
resources/osx/preinstall.erb

In a previous commit, service reloads were made unconditional,
as the test for loading them was failing. This updates the logic
to reload the services if they were loaded at the beginning of
the package operation.

(RE-6739) Make service load conditional on upgrade for osx

---

lib/vanagon/platform/windows.rb
spec/lib/vanagon/platform/windows_spec.rb

This function is necessary to facilitate the
windows vanagon work as WiX and windows require
only three digit versions with no non-digit chars.
This will also add rspec for the new function.

(maint) add windows style version function

---

CHANGELOG.md
resources/osx/postinstall.erb
resources/osx/preinstall.erb

The previous fix for the osx install scripts had some
syntax errors.
This fixes those and should actually produce a valid
shell script

OSX pre and post scripts should actually be shell

---

resources/windows/wix/project.wxs.erb

As per the original pxp-agent build, the Version for the MSI should be 3
digits and not 4. Use the new windows_style_version method provided by
PR: https://github.com/puppetlabs/vanagon/pull/326 to use the
first 3 digits only in the ERB project template.

(RE-6506) Change MSI Product Version to 3 digits.

---

lib/vanagon/platform/deb.rb

This allows cross-compiled packages to use correct tools (such as the
target arch strip command) when generating the package. When
project.noarch is set, this becomes a no-op.
Note: you cannot have a space between the -a and the arch, which
only works for the dpkg-buildpackage in Debian 8 and later.

(RE-6520) Specify arch when generating Debian pkgs

---

lib/vanagon/platform/windows.rb
resources/windows/wix/project.wxs.erb
spec/lib/vanagon/platform/windows_spec.rb

windows_style_version is misleading, as
there is more than one way to create a
windows package, this updates the name
to something specific to wix

(maint) update version function name

---

lib/vanagon/platform/windows.rb
resources/windows/wix/directorylist.wxs.erb

In order to facilitate the static file additions of
AppData to the puppet-agent project, this commit removes
the second run of heat.exe in the CommonAppDataFolder and
removes references of that folder from directorylist.wxs

(RE-6470) Remove second heat.exe run / AppData dirs

---

lib/vanagon/platform/windows.rb

As a way to differentiate between pftw MSIs and
vanagon msis (and allow us to put both through pipelines
while we test the cutover) add VANAGON to the vanagon
MSI filenames

(maint) add VANAGON to msi filename

---

lib/vanagon/component.rb
lib/vanagon/component/dsl.rb
lib/vanagon/project.rb
lib/vanagon/project/dsl.rb
resources/deb/control.erb
resources/rpm/project.spec.erb
spec/lib/vanagon/component/dsl_spec.rb
spec/lib/vanagon/project/dsl_spec.rb

Tested by adding conflicts to pl-tar and verifying with the dpkg and rpm commands that Conflicts were set appropriately.

(RE-6794) Add conflicts capabilities to our deb and rpm packages

---

resources/osx/postinstall.erb

Vanagon should not try to generate postinstall service stanzas
for OS X packages when there are no services to worry about.
Vanagon::Project#get_services will return an empty array if there
are no services, which evaluates to falsey in an `if` statement
so this should be a safe way to prevent this script from accidentally
generating invalid syntax in the Bash if/then block.

(RE-6100) OS X Service Postinstall fixup

---

lib/vanagon/project.rb

There was no need to follow previous behavior of making Conflicts
include packages specified in Replaces, so we are now keeping each
definition separate.

(RE-6882) do not copy package Replaces into Conflicts

---

lib/vanagon/project.rb
resources/osx/postinstall.erb
resources/osx/preinstall.erb

My previous OS X post-install fix was incomplete. This expands the use of the `#has_<values>?` boolean methods to help ensure that we don't accidentally construct empty `if`/`else` stanzas in our pre & post install scripts.
This is needed to help the PE Client Tools .pkg install successfully on OS X.

(RE-6100) Rub some booleans on the erb

---

lib/vanagon/project/dsl.rb
spec/lib/vanagon/project/dsl_spec.rb

We have tags that use double dashes, so this will make a version of .. so this fails when trying to make the RPM.

Reject empty strings so we dont get bad versions

---

lib/vanagon/component/dsl.rb
resources/solaris/11/p5m.erb

Currently, the solaris smf service uses a service type,
but the type is not being referenced in the calls to
the smf service handler.
This adds the service type to the service data structure
and uses it in the solaris smf service calls.

(RE-6739) Add service type for Solaris services

---

lib/vanagon/platform/windows.rb

We use vanagon's erb engine to populate fields
and remove sections based on platform. Thus we
do not need the -dplatform option in the WIX
compiler options.

(RE-6525) remove platform option from WiX

---

resources/deb/control.erb

In general, when you're using `Replaces` you also want to be using
`Breaks`. This adds `Breaks` into the control script, and also adds some
checking to make sure we aren't adding empty keys.

(CPR-330) Fixes for replaces in debian control script

---

lib/vanagon/project/dsl.rb

Because of the way we are using dsl objects in vanagon,
if you want an attribute to be accessible you need to
add a corresponding function to the dsl.rb in order to
set the attribute.
project.retry_count had no such function and so it was
not accessible

(maint) add retry_count to dsl

---

lib/vanagon/driver.rb

As pointed out by @cwood , the load_engine_object method is missing an
assignment to engine.

(maint) fix broken load_engine_object method

---

STYLEGUIDE.md

In an effort to make vanagon-based projects and components more readable
and consistent, this style guide was developed to suggest a logical
ordering and grouping of metadata.

(CPR-334) Style guide doc for vanagon-based projects

---

lib/vanagon/project/dsl.rb

for any attribute of the project object we require a subsequent method in the
dsl for project. This was missing for the timeout attribute

(maint) timeout not set in project dsl

---

lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb

With all the cross-compiling we're now doing, these methods will help us
to refactor vanagon-based component configs to improve readability.
Will remove the don't merge label once I've thoroughly tested this.

(RE-7015) Add is_cross_compiled utility matcher methods

---

lib/vanagon/utilities.rb
spec/lib/vanagon/utilities_spec.rb

Also, it seems like retry should raise the same error type as the
underlying command when available to avoid rogue rescues.

(CPR-336) Retry was not printing out error messages

---

CONTRIBUTING.md
README.md
vanagon.gemspec

Change all relevant references from puppetlabs to puppet. Change
any links to the correct new links

(PA-285) Branding name change

---

bin/build
bin/build_host_info
lib/vanagon/driver.rb
lib/vanagon/engine/base.rb
lib/vanagon/engine/docker.rb
lib/vanagon/engine/hardware.rb
lib/vanagon/engine/local.rb
lib/vanagon/engine/pooler.rb
lib/vanagon/project/dsl.rb
spec/lib/vanagon/driver_spec.rb
spec/lib/vanagon/engine/docker_spec.rb
spec/lib/vanagon/engine/hardware_spec.rb
spec/lib/vanagon/engine/local_spec.rb
spec/lib/vanagon/engine/pooler_spec.rb
vanagon.gemspec

Adds a `build_host` CLI for retrieving the type of build host for a vanagon project and platform to enable the following workflow:
```
$ bundle exec build_host puppet-agent el-7-x86_64
centos-7-x86_64
$ ~/bin/vmpooler.py -g centos-7-x86_64
vwoafc8cxlc8u03
$ bundle exec build puppet-agent el-7-x86_64 vwoafc8cxlc8u03
Executing 'rpm -q curl > /dev/null || yum -y install curl && ...
```

(QENG-3556) Add CLI for retrieving the type of build host

---

lib/vanagon/engine/ec2.rb
spec/lib/vanagon/engine/ec2_spec.rb

Commit bab55a46 had a trailing comma after `:instance_type`, which seems
to cause the following `initialize` method to be ignored. So trying to
create an EC2 engine and passing in a platform didn't work:
irb(main):033:0> Vanagon::Engine::Ec2.new(plat._platform)
ArgumentError: wrong number of arguments (1 for 0)
Commit b8f537a74 changed how engines return their name, so it's no
longer an instance variable. That combined with bab55a46, caused the
Ec2 engine to report its name as 'base':
irb(main):035:0> Vanagon::Engine::Ec2.new.name
=> "base"
This commit removes the trailing comma, fixes the engine name, and adds
a unit test to make sure we can create an EC2 engine and get the correct
name.

(maint) Add unit test for ec2 engine

---

USING_VANAGON.md
examples/resources/windows/wix/componentgroup.wxs.erb
examples/resources/windows/wix/project.wxs.erb
examples/resources/windows/wix/registryEntries.wxs.erb

These will eventually turn in to user docs for all of vanagon, but for now they
contain the user docs for creating a windows project with vanagon.

(maint) Add vanagon user docs

---

Gemfile
spec/lib/vanagon/engine/ec2_spec.rb

It's currently an optinal engine, and it should specify an optional dependency. This also makes the spec test for the EC2 engine option depending on whether or not the aws-sdk is available.
When this engine is declared a prime-time engine, the dependency on AWS-SDK should be moved directly into the Gemspec and this confinement should be removed.

(MAINT) Confine aws-sdk gem to bundler group

---

resources/rpm/project.spec.erb

brp-strip-static-archive causes cross-compiled static libs to end up
with "no machine" as their architecture, breaking builds.
With this fix, I'm now able to build all of the pl-build-tools targets for el-6-s390x. Going to run this through jenkins to ensure there are no regressions.

(maint) Disable brp-strip-static-archive from RPM builds

---

lib/vanagon/engine/ec2.rb

Iv realized after this was merged than when I try to access :symboles like id or private_ip_address that it doesnt work and fails out. So I just call the function directly then access them through there dot accesory.

Use id, private_ip address attrribute instead of symbol

---

bin/inspect
lib/vanagon/component.rb
lib/vanagon/extensions/hashable.rb
lib/vanagon/extensions/ostruct/json.rb
lib/vanagon/extensions/set/json.rb
lib/vanagon/extensions/string.rb
spec/lib/vanagon/extensions/ostruct/json_spec.rb
spec/lib/vanagon/extensions/set/json_spec.rb
spec/lib/vanagon/extensions/string_spec.rb
vanagon.gemspec

I haven't made a ticket for this yet; it's something I hacked together while working on refactoring how sources are handled. It seemed like it might be handy, so I thought I'd open up a PR and get some review on it before it's added to the code base.
---
This adds a new command to Vanagon, `inspect`. It takes two arguments: a project name, and a platform. It'll then dump a JSON formatted array of all of the components defined in the project. This can be filtered through `jq` for manual inspection or fed directly to other tools (if anyone writes then...).
```bash
mckern@flexo puppet-agent (git:master) $ bundle exec inspect puppet-agent osx-10.10-x86_64 | jq '.[] | select(.name == "ruby")'
```
```json
{
"name": "ruby",
"settings": {
"install_root": "/opt/puppetlabs",
"sysconfdir": …
```

(RE-4120) inspectable components

---

lib/vanagon/driver.rb
lib/vanagon/utilities.rb

Retries and timeouts can now be defined with the environment variables `RETRY_COUNT` and `TIMEOUT`. Useful for turning them up or down without having to commit a new value to a project every time you change it.
Also, the default retry count has been changed from 3 to 1. For _**reasons**_.

(MAINT) Finesse retries a little bit

---

lib/vanagon/driver.rb

When building toolchain components such as GCC, it takes more than 1
hours. This ups the default timeout to 2 hours since our jenkins configs
don't pass timeout as a parameter.

(maint) Increase default timeout

---

lib/vanagon/platform/osx.rb
resources/osx/uninstaller.tool.erb

For packages requiring extra steps in uninstallation, such as unloading
services, add an uninstaller to vanagon packages for OSX.

(PA-323) Update osx packaging to include an uninstaller

---

README.md
lib/vanagon/driver.rb

These are pretty common names, so we should try to minimize the
possibility of collision.
Also, added documentation for VANAGON_TIMEOUT environment variable,
which was previously undocumented.

(MAINT) Namespace VANAGON_TIMEOUT and VANAGON_RETRY_COUNT env. vars

---

resources/rpm/project.spec.erb

Prior to this commit, vanagon creates empty "install" and "upgrade"
files in the RPM localstatedir on all platforms. These files are created
for use by `%posttrans` scriptlets.
AIX and EL4 use an older version of RPM that does not support use of
`%posttrans`, so the state files are not needed on those platforms.
This commit updates vanagon's rpm spec template so the empty "install"
and "upgrade" files are not created on AIX and EL4.

(CPR-369) Don't create "install", "upgrade" files on AIX, EL4.

---

resources/rpm/project.spec.erb

Prior to this commit, on upgrade, services on AIX are not restarted, so
the old puppet and mcollective services may be left running.
This commit updates the `%preun` to stop AIX services also on upgrade.

(PA-390) On AIX, stop services also on upgrade.

---

lib/vanagon/platform/windows.rb
spec/lib/vanagon/platform/windows_spec.rb

It's posible to cause a failure in WiX by registering two services on paths
that are different but have the same named dir somewhere, for example,
registering two services under:
/dir/bin
/other_dir/bin
will cause a failure because when we create the directorylist.wxs file the
"bin" directories will both have the same "Id" field because we just used
name there. This commit appends values to the Id field that will ensure
uniqueness.
This commit upates both the windows platform object and rspec

(maint) Update the directorylist creation for windows to use uniq id

---

lib/vanagon/platform/windows.rb

During development of vanagon for windows platforms we added _VANAGON to the
output artifact names to differentiate between artifacts built by vanagon and
artifacts built elsewhere. remove this temporary change from production

(RE-7395) Update MSI output to remove _VANAGON from artifact

---

lib/vanagon/platform.rb
lib/vanagon/platform/deb.rb
lib/vanagon/platform/dsl.rb
lib/vanagon/platform/osx.rb
lib/vanagon/platform/rpm.rb
lib/vanagon/platform/solaris_10.rb
lib/vanagon/platform/solaris_11.rb
lib/vanagon/platform/windows.rb
spec/lib/vanagon/platform/deb_spec.rb
spec/lib/vanagon/platform/rpm_spec.rb
spec/lib/vanagon/platform/windows_spec.rb
spec/lib/vanagon/platform_spec.rb

In order to facilitate better output directory control, add the ability to
specify platform.output_dir in the platform config file and override any
defaults for output.
As part of this, to make vanagon more reusable, remove all platform specific
"defaults" that were there and create one single "default" for each platform
following the following pattern:
@platform/@platform_version/(optional)@target_repo/@plaform_arch

(maint) Update platform output directory

---

lib/vanagon/platform/windows.rb

currently puppet-agent needs package names of the form: name-version-arch.msi
instead of name-version.release-arch.msi. The need for this change to happen in
vanagon is a problem, but for now this update will have to suffice.

(maint) update windows package name

---

lib/vanagon/platform/deb.rb
lib/vanagon/platform/rpm.rb
spec/lib/vanagon/platform_spec.rb

We should maintain defaults while still making it easy to overwrite the output dir.

(maint) Revert change to default output dir

---

lib/vanagon/component/dsl.rb
lib/vanagon/component/source.rb
lib/vanagon/component/source/http.rb
lib/vanagon/utilities.rb
spec/lib/vanagon/component/source/http_spec.rb
spec/lib/vanagon/component/source_spec.rb

Before, we were only verifying http sources use md5. Modified vanagon to support multiple sum types by adding a sum_type parameter. We now support sha256, sha512, and md5.

(RE-5403) Modify Vanagon to support more than md5 sum

---

resources/rpm/project.spec.erb

Our cisco-5/7 build platforms are missing the definition of
__os_install_post, so we have to manually set it here. This
then enables the brp strip scripts, which are needed to reduce
the size of our agent packages for these platforms. This is
necessary as some targets will fail to even install the package
without stripped binaries because yum's package cache is kept
on a partition with ~50MB of free space.

(PA-569) Enable brp strip scripts for Cisco platforms

---

CHANGELOG.md

- Enable brp strip scripts for stripping binaries on Cisco RPM platforms
- MAINTAINERS file updated with current project maintainers
- Vanagon now supports sha256sum and sha512sum checksum validation in its DSL

(maint) changelog for 0.8.1

---

lib/vanagon/component/source.rb

Now that we support multiple checksum types for validating http sources,
assume md5 if sum_type isn't explicitly set.

(VANAGON-14) Use md5 as the default checksum type if not specified

---

.travis.yml
lib/vanagon/driver.rb
lib/vanagon/engine/always_be_scheduling.rb
lib/vanagon/engine/hardware.rb
lib/vanagon/engine/pooler.rb
lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb
spec/lib/vanagon/component/source/http_spec.rb
spec/lib/vanagon/driver_spec.rb
spec/lib/vanagon/engine/always_be_scheduling_spec.rb
spec/lib/vanagon/engine/pooler_spec.rb
spec/lib/vanagon/platform/dsl_spec.rb
spec/lib/vanagon/platform/windows_spec.rb
spec/lib/vanagon/utilities_spec.rb
spec/spec_helper.rb

We have an internal need for supporting the management of hardware build hosts through a common centralized scheduler, specifically [always-be-scheduling](https://github.com/puppetlabs/always-be-scheduling) (ABS).
Prior to this work, vanagon would manage hardware itself: configs would list the specific hardware resources which were known for building on a given platform/target. We would allocate the hardware instance, use the `lock_manager` to control access, etc.
In a world of scheduled hardware, allocation, lock management, setup, teardown, etc., are all Someone Else's Responsibility™.  This change allows authors to opt-in to an "always_be_scheduling" engine, which leaves the host management up to a third-party scheduler for certain platforms.
Additionally, as we wish …

(QENG-4456) sneak in support for scheduled hardware under a feature flag

---

resources/Makefile.erb

The makefile dependency for the bill-of-materials was being incorrectly specified, which meant that any project using it would have broken dependencies for `@name-project`. This commit ensures the bill_of_materials target matches the dependency listed in the `@name-project` target.

(maint) Fix bill-of-materials generation

---

README.md

When building multiple subsequent builds on a build
target things can go wrong. In particular the list
of files taken before and after the installation
phase can be quite easily incorrect.
Realistically the only way to be sure to be clean is
to reinstall the build machine.

Add note that build machines should be clean

---

bin/build
lib/vanagon/driver.rb
lib/vanagon/optparse.rb
lib/vanagon/project.rb
spec/lib/vanagon/project_spec.rb

The use case for devs is they need to only build a single component and it's
dependencies. This PR solves this by adding a filter_components function to
the project class that recursively compiles all the components build
dependencies (and the build dependencies' dependencies and so on) together in
to one array. The driver class will use that function and replace the project
objects' components array with the output of filter_components.
Vanagon is built well enough to handle the rest, all build steps and makefile
rules can remain the same.
This should be a strictly additive change, and should not affect any current
build processes.
Usage: bundle exec build <project> <platform> [--only-build <components>]
where <components> is a comma seperated list

(VANAGON-8) Add the ability to only build single components in vanagon

---

resources/rpm/project.spec.erb

This commit adds a dependency on `mkdir` and `touch`, as they are used in the
pre- and post-install script boilerplates, which then get used by every project.
In the future, we will supress pre/post scripts completely if there's nothing
specified by the project or the components.

(CPR-393) puppetlabs-release-pc1 RPM on centos5

---

lib/vanagon/engine/pooler.rb

This PR will look for the vmpooler auth token in `~/.vmfloaty.yml` if `~/.vanagon-token` is absent.

(maint) use .vmfloaty.yml if .vanagon-token absent

---

Gemfile
Rakefile
spec/spec_helper.rb

[Simplecov](https://github.com/colszowka/simplecov) allows us to start building rough metrics for how much code in Vanagon is actually tested. It's not bulletproof, but any measurement is probably better than no measurement.

(MAINT) Add Simplecov support to Rakefile

---

spec/lib/vanagon/component/source/http_spec.rb
spec/lib/vanagon/component/source/local_spec.rb
spec/lib/vanagon/component/source_spec.rb
spec/spec_helper.rb

Thanks to macOS' [System Integrity Protection feature](https://en.wikipedia.org/wiki/System_Integrity_Protection), assuming that writing to `/tmp` will probably let you down. Instead, we should call `mktemp -d` or using Dir.mktmpdir from within Ruby. Any tests that hardcoded `/tmp` as a value have been updated.

(MAINT) Fix tests that fail on macOS

---

.travis.yml
Rakefile

Vanagon uses the same group for :development and :test, so there's no
benefit to running Bundler with the `--without-development` flag.
The stubbed-out Git config during `before_check` has been updated to be
slightly more informative
Travis will now run the `test:spec` task instead of calling rspec
directly.
Travis is now unpinned from specific Ruby versions, using the aliases
for the x.y releases we actually care about.
This commit also includes a quick fix for the Rakefile: making sure
that Rubocop displays the names of failing cops by default.

(MAINT) Travis-CI fixups for the new Rakefile

---

lib/vanagon/component/dsl.rb
lib/vanagon/component/source/http.rb
lib/vanagon/engine/base.rb
lib/vanagon/platform/dsl.rb
lib/vanagon/project.rb
lib/vanagon/project/dsl.rb
lib/vanagon/utilities.rb
spec/lib/vanagon/component/source/http_spec.rb

This cleans up a lot of duplication and boilerplate with the abominable art of metaprograming. And while I was metaprogramming, I added some handy bumpers around our existing uses of `#method_missing?` (since newer versions of Rubocop will complain if they're not there).
Since this is just a proposal, please don't feel any intense pressure to merge it if you think it needs work, has rough edges, or makes things crappier to support. I welcome the conversation if you've got questions or concerns.

(Proposal) The Checksummoning

---

lib/vanagon/engine/pooler.rb
spec/lib/vanagon/engine/pooler_spec.rb

When token loading was refactored, this variable was missed. That
caused anyone using HEAD some lamentations and wailing when they tried
to load pooler tokens. The spec test for this functionality needs to
be refactored, but this is a blocking issue for at least one CI
pipeline.

(MAINT) Fix undefined variable in Pooler engine

---

spec/lib/vanagon/engine/pooler_spec.rb

When token loading was refactored, the coverage was not sufficient.
Failures were silently masked due to overly aggressive stubbing out of
test resources. The coverage for the way that the pooler engine
handles environment variables, a ~/.vmpooler-token file, and a
~/.vmfloaty.yml file has been rewritten completely to exercise the
intended functionality.

(MAINT) Improve spec coverage for token loading

---

lib/vanagon/component/dsl.rb
spec/lib/vanagon/component/dsl_spec.rb
spec/lib/vanagon/engine/pooler_spec.rb
spec/spec_helper.rb

The new token handling spec tests didn't quite mask pre-existing values all-the-way. So that's fixed. And it turns out that I broke checksum handling because you can't call `#gsub` on a Symbol. It's got to be cast to a String first. But while I was in there, I added some tests for that functionality because it's really important and I didn't realize it was untested.
Finally, I added a quick one-line update to `spec_handler.rb`, which will allow us to run individual spec tests much easier:
```bash
$ bundle exec rspec --order random --require spec_helper.rb ./spec/lib/vanagon/component/dsl_spec.rb
Randomized with seed 29687
....................................................................
Finished in 0.0873 seconds (files took 0.20678 seconds to load)
68 examples, 0 failures
Randomized …
```

0.9.0 was underbaked. I put it back in the oven.

---

CHANGELOG.md

We haven't remembered to update the links around the version numbers
for a little while. Oops.

(MAINT) Fix CHANGELOG links

---

lib/vanagon/platform.rb

Platform's accessors are overloaded and poorly structured. They don't
contain enough comments to make it obvious what each accessor is
intended for, and this is causing drag when we try to
add/expand/improve platform attributes. This commit should at least
lower the cognitive barrier & load required to understand what these
accessors do.

(MAINT) Reorganize & comment Platform accessors

---

bin/render
lib/vanagon/driver.rb
vanagon.gemspec

`render` will generate just the Makefile for a given Vanagon project and place it in a temporary directory, where it can be inspected without interrupting/halting/aborting a project build. It will install no dependencies, and do no engine/build target provisioning. This is intended to help developers fine-tune any project changes that would affect the Makefile before a project is built. The previous PR was closed while a quirk related to options hashes was fixed, and it can't be reopened so I started a new PR.

(FEATURE) Add `render` command

---

lib/vanagon/platform.rb

Make method name more canonical to what the system actually is.
Added a deprecation warning if is_osx? is still used and then calls is_macos?

(VANAGON-28) Rename is_osx? helper to is_macos?

---

lib/vanagon/driver.rb

Looks like Vanagon is missing a bunch of the data that a Makefile
would need to contain (directory names, unpacking methods, etc.) until
we remote sources are retrieved. This is a short-term workaround until
the source handling is smart enough to work from its metadata.

(MAINT) `Driver#render` is incomplete

---

.rubocop.yml
Gemfile

Keeping Rubocop up to date will probably hurt less if we do it
more often.

(MAINT) Update Rubocop to 0.47.x

---

lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb
lib/vanagon/platform/rpm.rb
spec/lib/vanagon/platform/rpm_spec.rb
spec/lib/vanagon/platform/windows_spec.rb

This commit adjusts how `dist` is defined for rpms. We now only use `os_name`
and `os_version` to construct `dist` if it isn't otherwise specified. This will
allow us to change the fedora distro tags without disrupting the way other
distro tags are currently defined.

(CPR-391) Fedora packages have odd distro tag

---

spec/lib/vanagon/component_spec.rb
spec/spec_helper.rb

As per PR #448, we need some test coverage in `Vanagon::Component`, specifically around `#get_sources`. So here's an initial test, which validates existing behavior (before we start changing it). Also included:
- Simplifications for the tests that already existed for `Vanagon::Component`
- A minimum score for test coverage, and the option to enforce it

Let's test Vanagon::Component (more than we do)

---

lib/vanagon/environment.rb

The shell variable mangling had a bad iterator. That's fixed.

(MAINT) Fix variable typo in Environments

---

README.md
bin/build
lib/vanagon/driver.rb
lib/vanagon/engine/always_be_scheduling.rb
lib/vanagon/engine/base.rb
lib/vanagon/engine/docker.rb
lib/vanagon/engine/ec2.rb
lib/vanagon/engine/hardware.rb
lib/vanagon/engine/local.rb
lib/vanagon/engine/pooler.rb
lib/vanagon/optparse.rb
spec/lib/vanagon/driver_spec.rb

From @adreyer:
> I'd like to be able to specify the remote_workdir on the build build box so that all dependencies and make files remain in place and I can rebuild specific components quickly. For example when working on puppet-job for windows this allows me to quickly provision a build box on which I can recompile in a few seconds.
I pulled in his commit, rebased it, and now it just needs a spec test (pending).

Add '--remotedir' to build command

---

CHANGELOG.md
lib/vanagon/component/dsl.rb

An array has no key or value, so this obviously won't work. I'm pretty
embarrassed that this was missed.

(MAINT) Fix egregious logic error in comp. DSL

---

lib/vanagon/component/dsl.rb
spec/lib/vanagon/component/dsl_spec.rb

These options are already supported when creating files, but not
supported in the wrapper that creates configfiles. You want to be able
to set these options for config files.

(maint) Allow owner, group, and mode to be passed to configfiles

---

resources/Makefile.erb
resources/rpm/project.spec.erb

If we're linking a directory we only want to add the link, not all of
the files inside the linked directory.

(maint) Don't follow symlinks while making file lists

---

README.md
lib/makefile.rb
lib/vanagon/component.rb
lib/vanagon/component/source/local.rb
lib/vanagon/driver.rb
lib/vanagon/engine/base.rb
lib/vanagon/engine/local.rb
lib/vanagon/environment.rb
lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb
lib/vanagon/project/dsl.rb
resources/Makefile.erb
resources/metrics/profiling_shell.sh
resources/rpm/project.spec.erb
spec/lib/makefile_spec.rb
spec/lib/vanagon/environment_spec.rb

There are refinements needed to metric retrieval now that they're being batched to single-field CSV files on the remote build target -- they will be in a follow-up PR.

(VANAGON-47) Vanagon 0.10.0 is embarrassingly broken

---

lib/vanagon/platform.rb
lib/vanagon/platform/deb.rb
lib/vanagon/platform/rpm.rb
lib/vanagon/project.rb
lib/vanagon/project/dsl.rb
resources/deb/rules.erb
resources/rpm/project.spec.erb
spec/lib/vanagon/project/dsl_spec.rb

For some projects you may need to set custom variables/defines/etc in
your RPM spec file or debian rules file. This allows you to pass
arbitrary strings that will get added to those files.
TODO:

(maint) Allow passing of custom build variables

---

lib/vanagon/driver.rb
lib/vanagon/environment.rb
lib/vanagon/project.rb
resources/windows/nuget/project.nuspec.erb
spec/lib/vanagon/environment_spec.rb

Thanks to an ungreedy (generous?) regular expression, not every value in an environment variable was being coerced. The generous regex has been updated, but while I was in there I flushed out a couple of typos and a few places where we'd hardcoded variables for the underlying shell instead of Make.

(VANAGON-47) Env. var. fixups

---

lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb
lib/vanagon/project/dsl.rb
spec/lib/vanagon/project/dsl_spec.rb

This also includes some reorganizing of Platform/Platform::DSL so we can use our handy version_from_branch to add versioned repos from our project definition!
TODO:

(maint) Add capability to figure out version from branch

---

lib/vanagon/component.rb
spec/lib/vanagon/component_spec.rb

Before, if a second source was compressed it could not be unpacked because we assumed it was along the lines of a conf file. Now handles second sources that are archives and unpacks them appropriately. Spec tests were also added to ensure that the secondary source was added and unpacked properly.
Previous discussion of this PR can be found [here](https://github.com/puppetlabs/vanagon/pull/448)

(RE-5646) add_source unpacks compressed second source & added spec tests

---

CHANGELOG.md
README.md
bin/build
lib/vanagon/driver.rb
lib/vanagon/optparse.rb
spec/lib/vanagon/component/source/git_spec.rb
spec/lib/vanagon/driver_spec.rb

This PR changes `--remote_workdir` to `--remote-workdir`, updates the appropriate tests, and fixes a couple of typos. THEN it updates the CHANGELOG for a pending 0.11.0 release.

Rename `--remote_workdir` and update CHANGELOG

---

lib/vanagon/component.rb
lib/vanagon/component/dsl.rb

We allow the user to set dirname in case they are dealing with a source
that unpacks into a directory that's different than the name of the
archive. However, we don't honor this. The code always overwrites that
user-set variable with what it thinks it should be. That's lame.
This commit fixes how that variable is treated. If the user does in fact
supply `dirname` in the component config, then that variable assignment
will be honored. Otherwise, it defaults to use the same name as the
original archive.

(maint) Ensure dirname override will be honored

---

bin/build
bin/build_host_info
bin/devkit
bin/inspect
bin/render
lib/vanagon/component/source/http.rb
lib/vanagon/utilities.rb
spec/lib/vanagon/component/source/git_spec.rb

Since we outsource git repo handling to a 3rd party library, we don't have to test every single aspect of our wrapper. Just ensuring that it talks to the underlying Git library should be sufficient.
The benefit is that unit test run time drops from about 7 seconds to consistently less than 1 second. A win is a win, right?

(MAINT) Git tests shouldn't hit the network

---

Rakefile
bin/build
bin/build_host_info
bin/devkit
bin/inspect
bin/render
lib/vanagon/component/dsl.rb
lib/vanagon/component/rules.rb
lib/vanagon/component/source.rb
lib/vanagon/component/source/http.rb
lib/vanagon/component/source/local.rb
spec/lib/vanagon/component/dsl_spec.rb
vanagon.gemspec

Some packaging installs service files as links to executables. This
commit adds the `link_target` keyword argument to install_service. If
`link_target` is specified the specified `service_file` will be
installed at the location in `link_target` and the target service file
will be a symlink to the `link_target`.

(maint) Add ability to install service as a link

---

resources/rpm/project.spec.erb

AIX doesn't track the entire filesystem in the RPM database, so
there's a number of core system files that are not exposed to RPM and
should not be used as a constraint for dependencies. `/bin/touch` and
`/bin/mkdir` are two of them. We should stop requiring those files as
dependencies for AIX RPMs.

(VANAGON-55) Fix AIX RPMs requirements

---

lib/vanagon/patch.rb
spec/lib/vanagon/component/rules_spec.rb

Prior to this commit, if a patch wasn't perfectly cleanly applied, the
patch command would create a .orig file. This often would happen if
the patch was offset by some amount. This commit updates the patch
process to prevent that backup file from being created. We don't need
that, given that we're working on a throwaway system. If the patch can't
apply, it'll throw an error. If it does apply, even if there's an offset
issue, we don't need to save that backup file.

(maint) Do not create any backup files on patch

---

lib/vanagon/component/source/git.rb
spec/lib/vanagon/component/source/git_spec.rb

Fun fact: When building on OSX your tmpdir is going to end up in /var
which is actually a symlink to /private/var. If you don't chdir / set
your workdir to the realpath of your tmpdir git will fail with
fatal: Could not chdir to
'../../../../../../../../../../../private/var/folders...'
if you are using the `--git-dir` option. The ruby-git library we use
appends `--git-dir` to each git command. So, when initializing the git
objects we need to make sure we're using the `File.realpath` so we don't
trigger this weird issue when trying to update submodules.
Big thanks to @mckern for helping me track this issue down.

(maint) Fix for workdir with symlinks

---

bin/build
bin/build_host_info
bin/devkit
bin/inspect
bin/render
lib/vanagon/component.rb
lib/vanagon/component/source/git.rb
lib/vanagon/component/source/http.rb
lib/vanagon/component/source/local.rb
lib/vanagon/driver.rb
lib/vanagon/engine/ec2.rb
lib/vanagon/engine/hardware.rb
lib/vanagon/engine/pooler.rb
lib/vanagon/optparse.rb
lib/vanagon/platform.rb
lib/vanagon/project.rb
lib/vanagon/project/dsl.rb
lib/vanagon/utilities.rb

I'm not in love with this approach, but it's not drastically different
than how Vanagon handled notification/informing users of state/status
previously. The only difference is now the output is explicit, and can
be more easily/predictably filtered. I think that this is a hold-over
bandaid until we've got a better logging/notification system in place
in Vanagon but it should address the concerns in VANAGON-57.
As is, I'm not wedded to this approach and I'd love to hear any ideas anyone else has.

(VANAGON-57) inform on STDERR, not STDOUT

---

examples/components/component1.rb
examples/components/component2.rb
examples/projects/project.rb
lib/vanagon/component.rb
lib/vanagon/component/dsl.rb
lib/vanagon/component/source.rb
lib/vanagon/component/source/local.rb
lib/vanagon/component/source/rewrite.rb
lib/vanagon/project/dsl.rb
spec/lib/vanagon/component/source/rewrite_spec.rb
spec/lib/vanagon/component/source_spec.rb
spec/lib/vanagon/component_spec.rb

The rewrite engine in Vanagon is not popular. It's made hitting
internal mirrors easier for Puppet but it's made building Puppet Agent
harder for many of our customers. I've been planning on adding Mirror
URL support for a while now... and that day is today.
Mirror URLs will deprecate rewrite rules, and provide flexibility for
multiple mirrors (if so desired). There's a new DSL method, and some
backend code, and deprecated-but-preserved backwards compatibility for
any projects that aren't likely to be able to move forward quickly.
Checklist:

(VANAGON-56) Introducing Mirror URLs

---

Gemfile
lib/vanagon/platform.rb
lib/vanagon/platform/deb.rb
lib/vanagon/platform/dsl.rb
lib/vanagon/platform/rpm.rb
lib/vanagon/project.rb
lib/vanagon/project/dsl.rb
spec/lib/vanagon/platform/rpm_spec.rb
spec/lib/vanagon/platform_spec.rb
spec/lib/vanagon/project/dsl_spec.rb

Sometimes it's useful to be able to generate .src.rpm and
.dsc/changes/etc. This adds the ability to do that.

(maint) Add ability to generate source artifacts for rpm/deb

---

lib/vanagon/component/source/git.rb

Since Git::GitExecuteError is referenced within a class named Git, we
need to fully qualify it, otherwise, we get:
error uninitialized constant Vanagon::Component::Source::Git::GitExecuteError

(maint) Fully qualify Git::GitExecuteError

---

lib/vanagon/component.rb
lib/vanagon/platform.rb
lib/vanagon/project.rb

The filename and lineno params to #instance_eval were not being set
correctly, so the location indicated by the backtrace as the source of
an exception is not correct. This also confuses pry if you try to debug
your config file.
Not sure where a good place to add tests for this would be but happy to do so if someone can make a suggestion.

Fix backtraces from exceptions thrown from config files.

---

.rubocop.yml
lib/vanagon/component/dsl.rb
spec/lib/vanagon/component/dsl_spec.rb

Currently the owner/group/mode is set in the inidividual post-install
steps based on platform. However, some platforms do not have this
implemented. We can work around this by setting owner/group/mode when we
install files and directories on the build environment.
This seems to at least fix an issue with mode not being set for osx.
More in-depth testing should be done though.

(VANAGON-49) install_file isn't respecting owner/group/mode

---

resources/rpm/project.spec.erb

Previously, we created AIX services once at install, but did
not have correct logic to update them if they changed. This
adds the necessary logic to reconfigure AIX services.

(VANAGON-62) Update AIX services on package upgrade

---

lib/vanagon.rb
lib/vanagon/component.rb
lib/vanagon/driver.rb
lib/vanagon/project.rb
spec/lib/vanagon/project_spec.rb

This commit adds in the ability for vanagon to generate additional build
data for downstream package promotion consumption.

(VANAGON-63) Generate additional build metadata

---

lib/vanagon/component.rb

While refactoring the `get_dependency_hash` function I accidentally
dropped the url parameter. This commit adds that back in.

(maint) Add url to dependency hash

---

resources/deb/postinst.erb

Bash doesn't like empty if statements

(VANAGON-109) Fix postinst to not break for empty trigger scripts

---

resources/rpm/project.spec.erb

Found as
```
warning: File listed twice: /opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/mini_portile2-2.3.0/test/assets/test mini portile-1.0.0/configure
```
See these bash experiments:
```
david@davids:~/git/vanagon$ echo "a b" >> ../tmp/quux
david@davids:~/git/vanagon$ echo "c d" >> ../tmp/quux
david@davids:~/git/vanagon$ for i in `cat ../tmp/quux`; do echo $i; done
a
b
c
d
david@davids:~/git/vanagon$ for i in "`cat ../tmp/quux`"; do echo $i; done
a b c d
david@davids:~/git/vanagon$ while read i; do echo $i; done < ../tmp/quux
a b
c d
david@davids:~/git/vanagon$
```

(maint) avoid duplicate file errors when directory names contain spaces

---

lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb
lib/vanagon/platform/osx.rb
lib/vanagon/platform/rpm/aix.rb
lib/vanagon/platform/solaris_10.rb

In order to validate that the archive has the contents we expect it to, we generate the sha1 sum at build time for verification at build time of the parent project.

(VANAGON-111) Generate a sha1 sum at build time

---

lib/vanagon/platform/windows.rb
spec/lib/vanagon/platform/windows_spec.rb

Due to the nature of how windows builds work, several of the packaging
steps will fail without the resources/windows/wix or resources/windows/nuget
directories. This commit adds the 'archive' package type, intended for
use when you're only generating the compiled archive. This package type
lets you skip over the generate_*_package and
generate_*_packaging_artifacts methods.

(maint) Add 'archive' package type for windows

---

lib/vanagon/utilities.rb

Getting an error message is cool, but without the backtrace of what
actually went wrong it's really hard to debug.

(maint) Print backtrace if retry-on-fail fails

---

lib/vanagon/platform.rb

The way we were populating the compiled archives in the past caused failures on Solaris. The version of `gtar` on Solaris 10 and 11 claims to support the `-C` flag to change directories prior to adding files, however this ends up giving errors about the directories not being found. Since each line of the makefile executes in a separate shell anyways, let's just `cd` prior to generating the tarball to simplify the commands.

(maint) Simplify compiled archive generation

---

lib/vanagon/component/source/http.rb
spec/lib/vanagon/component/dsl_spec.rb
spec/lib/vanagon/component/source_spec.rb

This adds the ability to set the `sum` for a component to the url of a
file containing the checksum rather than the actual checksum.

(VANAGON-111) enable consumption of remote checksums

---

lib/vanagon/engine/pooler.rb
lib/vanagon/utilities.rb

This commit adds the ability to pull hosts from the nspooler as well as the
vmpooler. The way this works is simple: the pooler engine now checks both the
vmpooler and nspooler for hosts, and if the response is 'ok'='false' vanagon
just moves on to try the second pooler

(maint) Add nspooler support in vanagon for checking out from nspooler

---

bin/ship

A generic `rescue` statement does not catch LoadErrors which causes this
to fail loudly with a stack trace if you don't have artifactory.

(maint) Explicitly rescue LoadError while shipping to artifactory

---

README.md

The Overview section is probably the most important section for someone trying to understand how Vanagon works.
This also switches the links in the README to relative links.

Move Overview section up in the README

---

lib/vanagon/engine/base.rb
lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb
lib/vanagon/platform/osx.rb
lib/vanagon/platform/rpm/wrl.rb
lib/vanagon/platform/solaris_10.rb
resources/Makefile.erb
spec/lib/vanagon/platform/osx_spec.rb

OSX doesn't support the mktemp flags we use on other platforms, so
specify the correct flags for OSX, and allow mktemp to be overwritten in
platform definitions.

(VANAGON-108) Allow for customizable mktemp

---

lib/vanagon/platform.rb
lib/vanagon/platform/deb.rb
lib/vanagon/platform/dsl.rb
lib/vanagon/platform/rpm/aix.rb
lib/vanagon/platform/solaris_10.rb
resources/Makefile.erb
resources/rpm/project.spec.erb
spec/lib/vanagon/platform/rpm/aix_spec.rb
spec/lib/vanagon/platform/solaris_10_spec.rb

We use some functionality only present in GNU sed. Previously the paths
were just hard-coded in relevant places, but this adds the ability to
specify the location for GNU sed for a platform.

(VANAGON-69) Add the ability to specify sed for platform

---

lib/vanagon/driver.rb
lib/vanagon/project.rb
spec/lib/vanagon/driver_spec.rb

Previously, Vanagon would retry fetching all sources as a single
block. This could confuse debugging of failed fetches, since it's
possible for a differnt source to fail in the retry than in the
original run. It also (paradoxically) increased the chances for an
overall job failure, since successful downloads were given another
change to break.
This change causes Vanagon to retry fetching each component
individually, giving each an opportunity to succeed, and making
debugging cleaner when fetches fail.
Since on most platforms build dependencies are install in a single
package manager transaction, that is still treated monolithically in
the driver.

(VANAGON-116) Retry source fetches individually

---

lib/vanagon/component/source.rb

The individual source types will coerce the passed url into a URI if
needed, but when determining the source type we want to work with
strings so we can do pattern matching.

(maint) Convert URIs to Strings before figuring out source type

---

resources/rpm/project.spec.erb

Previously, Vanagon ran postinstall scripts for upgrades in the
postuninstall phase. This meant that any postinstall scripts would
always be sourced from the /previous/ version of a package,
which makes it rather difficult to fix bugs in the script or to
change the contract between a preinstall and postinstall phase.
This runs those scripts in the expected phase of the RPM
transaction.

(VANAGON-120) Run postinstall scripts in the postinstall phase

---

resources/rpm/project.spec.erb

In VANAGON-120, we moved postinstall upgrade scripts from the postun
step to the post step, so that they would always come from the new
version of the package, instead of the old. Unfortunately, vanagon
historically has had an unconditional service stop in the preun for
AIX. This meant that when upgrading from older packages, the services
we restart in post would be stopped again in preun.
We need to ensure we can still run the version of the script that
comes with the new package, but do so after the old package's
aggressive preun has run. To do that, the new package registers a
triggerpostun handler for its own name. This handler will be run from
the new package near the end of the transaction - after the old
package's preun and postun scripts.

 (VANAGON-125) Move AIX postinstall scripts to 'triggerpostun'

---

lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb

redhatfips is a platform based on redhat with FIPS features enabled. We
treat it as a separate platform due to its unique build requirements.

(PA-1958) Add redhatfips as an RPM platform

---

bin/sign
vanagon.gemspec

Before, we would build a package, ship it to builds, and if we wanted to sign
and ship it we did that as a collective step. Now, you can sign your package
before shipping anywhere, just run `bundle exec sign`
Before:
```
sara@sara:~/puppetlabs/pl-build-tools-vanagon/pkg$ rpm -qpi pl-rust-1.18.0-2.sles12.x86_64.rpm
Name        : pl-rust                      Relocations: (not relocatable)
Version     : 1.18.0                            Vendor: Puppet Labs
Release     : 2.sles12                      Build Date: Fri Mar 16 10:52:10 2018
Install Date: (not installed)            Build Host: u194ti5q5c11og7.delivery.puppetlabs.net
Group       : System Environment/Base       Source RPM: pl-rust-1.18.0-2.sles12.src.rpm
Size        : 331792277                        License: Apache 2.0 and MIT …
```

(RE-10422) Make separate signing step before shipping to builds

---

lib/vanagon/component.rb
spec/lib/vanagon/component_spec.rb

Going to work on adding a couple tests in the morning.

(VANAGON-75) Fail build explicitly when patch filenames conflict

---

lib/vanagon/platform.rb
lib/vanagon/project.rb

When using a custom project bill-of-materials path for precompiled archives, the bill-of-materials file was not correctly removed from the compiled archive, and thus conflicts with projects using the archive with the same custom bill-of-materials path.
The files added to the tarball should include the path to the bill-of-materials, not just the default bill-of-materials location.

(maint) Fixes for custom bill-of-materials paths

---

lib/vanagon/project.rb

When creating the tar, the list of files will be passed in to a tar
command that looks like `'tar' -cf - -T <files>`. If the file-list is
not the first entry of that array, the tar command will be malformed and
will not include the correct files.

(maint) Pass the file list in before the bill of materials

---

lib/vanagon/component.rb
lib/vanagon/component/dsl.rb
lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb
lib/vanagon/project.rb
resources/deb/postinst.erb
resources/deb/postrm.erb
resources/deb/prerm.erb
resources/rpm/project.spec.erb
spec/lib/vanagon/component/dsl_spec.rb
spec/lib/vanagon/platform_spec.rb

Debian in particular supports running modern systems under either
systemd or sysv. This adds support for passing multiple servicetypes in
your platform definition and also installing multiple services.

(VANAGON-123) Add support for multiple service types

---

resources/rpm/project.spec.erb

* Removes redundant `PATH` modification (that directory is added to `PATH` earlier in the script and exported
* sed command changed to search for lines matching the entry before applying the substitution (much faster than attempting the substitution globally)
* sed substitution changed to not use a match group (prefixing a line can slightly more efficiently done by replacing the start of the line with the desired prefix).
These changes resulted in an average drop of just under 6 minutes in build time for the PDK RPMs on EL7. I extracted the resulting packages and confirmed that they all contained the same files.
This could probably be optimised further in the future by replacing the loop entirely with an awk script that looped through the file list and statted each entry to build the …

(maint) Optimise looped sed call

---

lib/vanagon/project.rb

Paths were incorrectly determined when inheriting yaml settings from a
local file source.
I messed this up at some point while refactoring https://github.com/puppetlabs/vanagon/pull/566 -- I've tested these changes with local and http settings URLs in puppet-agent.

(VANAGON-131) Fix yaml load paths for load_yaml_settings

---

lib/vanagon/component.rb
lib/vanagon/component/dsl.rb
lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb
lib/vanagon/project.rb
resources/deb/postinst.erb
resources/deb/postrm.erb
resources/deb/prerm.erb
resources/rpm/project.spec.erb
spec/lib/vanagon/component/dsl_spec.rb
spec/lib/vanagon/platform_spec.rb

`/run/systemd/system` is not a reliable way to determine if systemd is
enabled on Debian systems, especially when using chroots or when using
a Debian preseed file.
This reverts commit 56bbacb18685d2b87398eab6d78718d9b4e36f5c, reversing
changes made to d71cdc5d6601dcdaa30d61d79d7682e2a79944ff.

Revert "Merge pull request #556 from underscorgan/tickets/master/vanagon-123-deb-no-systemd"

---

lib/vanagon/engine/local.rb
spec/lib/vanagon/engine/local_spec.rb

The method signature for `retrieve_built_artifact` changed in
https://github.com/puppetlabs/vanagon/commit/0d841370852b9d4666adc0a0d63ccebafa3f0d52,
but it was not updated for the local engine. This updates the local
engine to match the new method signature.

(VANAGON-139) Update `retrieve_built_artifact` for the local engine

---

examples/platforms/windows-platform.rb

- Add the --no-progress switch in an effort to shrink the size of
build logs. Choco describes the feature as:
Do Not Show Progress - Do not show download progress percentages.
Currently, build logs include extremely verbose output when choco
packages are downloading, adding many lines per each 1% of a given
package download. This commit removes that extraneous output.

(maint) Disable choco download progress in example

---

lib/vanagon/project.rb

As we move towards using the new metadata service, files that previously lived
in the `ext` directory may be removed, removing the whole directory as well.
This commit ensures that the `ext` directory is created before trying to write
a new file to it.

(RE-11270) Create `ext` directory before writing build_metadata

---

bin/build_requirements
vanagon.gemspec

Sometimes it's useful to list the external build requirements (those that
aren't other components) of a project. This commit adds the build_requirements
command to vanagon to list out a sorted array of those requirements

(maint) Add build_requirements command

---

README.md
lib/vanagon/component.rb
spec/lib/vanagon/component_spec.rb

This commit adds a VANAGON_USE_MIRRORS environment variable that can be used
to skip fetches from internal Puppet Inc. mirrors.

(VANAGON-122) Add VANAGON_USE_MIRRORS env variable

---

resources/solaris/11/p5m.erb

puppet-agent deployment fails on Solaris 11.4 with the following error:
```
root@rf8l60qft5p9c7f:~/mitza# pkg install puppet-agent@6.0.2.88.50778,5.11-1
Creating Plan (Merging actions): |
pkg install: The package pkg://puppetlabs.com/puppet-agent@6.0.2.88.50778,5.11-1:20181017T124140Z delivers items to reserved directories and can not be installed.
The following items are delivered to reserved directories:
dir system/volatile/puppetlabs
```
This is because system/volatile is considered a "reserved" directory and no Solaris packages should deliver contents into it. 
If an application needs to have the PID file into this folder, it should handle this in its init script. Example:
- https://github.com/puppetlabs/puppet/pull/7176/files#diff-6a024706b7725919079035ac75eb7621R29
- …

Solaris packages should not create content in system/volatile

---

lib/vanagon/platform/osx.rb

WIP: add specific command for installing build dependencies on osx
This is run if you do not call platform.install_build_dependencies_with
For now is used only by osx-10.12
Related PR's:
https://github.com/puppetlabs/puppet-runtime/pull/113
https://github.com/puppetlabs/puppet-agent/pull/1568

(PA-1272) Refactor our use of homebrew to not run as root

---

resources/rpm/project.spec.erb

Fedora 29 has a symlink for /bin to /usr/bin which breaks the rpm installation
fix: use /usr/bin when building for fedora-29

(PA-2231) Add Fedora 29 (x86_64) support

---

lib/vanagon/project.rb
resources/rpm/project.spec.erb
resources/solaris/10/pkginfo.erb
resources/windows/nuget/project.nuspec.erb
spec/lib/vanagon/project_spec.rb

This commit replaces several instances of regex matching on the vendor field
with methods `vendor_name_only` and `vendor_field_only` to parse out either just
the name or just the email address, respectively, from a vendor value of the
form 'Name of Vendor \<email@vendor.com\>'.
This commit also adds a `vendor=` setter to the `Vanagon::Project` class in
order to validate that the vendor value is of the appropriate form. Previously,
if the email portion was not included, erb template parsing would fail with
"undefined method `[]' for nil:NilClass". Now we provide a helpful error message
if the vendor value is not of the correct form.

(VANAGON-146) Improve parsing of project vendor field

---

resources/rpm/project.spec.erb

If you're trying to set additional defines/globals/etc that are called
during the `__os_install_post`, those need to be set before we reset
`__os_install_post` for debug symbol stripping.

(maint) Move `package_overrides` higher up in the RPM SPEC file

---

lib/vanagon/platform/osx.rb

Build tested with puppet-agent but had trouble with testing signing:
Executing 'set -e; mkdir -p /tmp/6092442922992217/mount /tmp/6092442922992217/signed' on -i /home/jenkins/.ssh/id_signing jenkins@osx-signer.delivery.puppetlabs.net
Warning: Identity file /home/jenkins/.ssh/id_signing not accessible: Permission denied.
Permission denied (publickey,gssapi-with-mic,keyboard-interactive).
rake aborted!
If anyone knows the way to fix this, I can re-test.

RE-12096 Set filesystem type when creating OSX packages

---

resources/rpm/project.spec.erb

This commit updates the rpm spec file template to disable automatic shebang
munging, which was introduced in Fedora 28 and RHEL 8. Without this, certain
builds fail on these platforms because the python shebang gets munged
ambiguously. For more info, see
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/2PD5RNJRKPN2DVTNGJSBHR5RUSVZSDZI/.

(VANAGON-147) Disable automatic shebang munging

---

lib/vanagon/engine/docker.rb

Docker requires container names to match the following regular expression:
[a-zA-Z0-9][a-zA-Z0-9_.-]
Vanagon will violate this when it attempts to launch a container from an
image like `amd64/debian:9-slim` as the container is named by appending
`-builder` to the image name. This commit updates the Docker engine to
sanitize the name given to Docker containers by replacing `/` and `:`
characters with underscores.

(VANAGON-101) Sanitize docker container names

---

lib/vanagon/engine/docker.rb
lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb

This commit updates the Platform DSL to include a new `docker_run_args` method.
This method can be used to specify an additional list of CLI arguments that
the Docker engine will pass to `docker run` when creating containers.

(VANAGON-150) Allow platforms to specify docker run args

---

lib/vanagon/component.rb
lib/vanagon/component/dsl.rb
spec/lib/vanagon/component_spec.rb

This will allow us to force an additional clone of git sources to
determine the version while the component is still being processed. This
is needed to allow for including the component version in the gemspec
file for facter, puppet, and hiera so that ruby correctly identifies
those as installed gems.

(PA-2670) Add support for `get_version_forced` in the vanagon component

---

lib/vanagon/engine/docker.rb

This commit updates the Docker engine to add a 1 second sleep after each
SSH failure while waiting for the container to start up. This gives SSHD
a chance to start up before Vanagon retries the command.

(VANAGON-151) Wait for SSHD to start in containers

---

lib/vanagon/component/dsl.rb
lib/vanagon/platform/solaris_11.rb

When upgrading the puppet-agent package, Solaris 11 doesn't automatically restart a service if the SMF manifest contains no changes.
This commit runs a sed on the target service(s) to change the current version (which is always 1) to the puppet-runtime version (since `version` is expected to be an integer value, per SMF documentation).
This commit also changes the Solaris sed to `/usr/gnu/bin/sed` which is the GNU implementation, so that we benefit from in-place editing and extended regular expressions.

(VANAGON-153) Update version in SMF manifest

---

lib/vanagon/component/dsl.rb

Given that multiple component versions can be released using the
same puppet-runtime version, we should use UNIX time to ensure no two
releases have the same version.
This also satisfies the SMF constraint that the `version` field should
be an integer.
Tested on Solaris 11.

(VANAGON-153) Use UNIX time for smf version

---

resources/rpm/project.spec.erb

The existing method of scanning through the file list to find
directories is painfully slow for the PDK builds which contain tens of
thousands of small files.
```
$ time while read entry; do if [ -n "$entry" -a -d "$entry" -a ! -L "$entry" ]; then sed -i "\|^$entry\$|s|^|%dir |" file-list-for-rpm.sed; fi; done < file-list-for-rpm.sed
real	31m31.287s
user	13m18.240s
sys	18m13.089s
```
By rewriting this to use Perl instead, we can eliminate the fork & execs
for each entry in the file list and drastically speed this process up.
```
$ time perl -i -lne 'if ((-d $_) && !(-l $_)) { print "%dir $_" } else { print }' file-list-for-rpm.perl
real	0m0.246s
user	0m0.060s
sys	0m0.179s
```
Both processes started with the same file list (copied with different
extensions for illustrative purposes) and …

(maint) Faster file-list-for-rpm modification with perl

---

lib/vanagon/platform/deb.rb

When using `add_build_repository` which is installing curl,
puppet-agent jobs hangs becasue the interactive mode is asking to restart some services:
```There are services installed on your system which need to be restarted when
certain libraries, such as libpam, libc, and libssl, are upgraded. Since these
restarts may cause interruptions of service for the system, you will normally be
prompted on each upgrade for the list of services you wish to restart.  You can
choose this option to avoid being prompted; instead, all necessary restarts will
be done for you automatically so you can avoid being asked questions on each
library upgrade.
Restart services during package upgrades without asking? [yes/no]```
This commit ads `noninteractive` to curl install command

(maint) add noninteractive to apt curl install

---

lib/vanagon/platform/dsl.rb

Building puppet runtime for windowsfips fails with the following error:
```04:29:32 Error loading platform 'windowsfips-2012r2-x64' using '/tmp/jenkins/workspace/platform_agent-runtime_runtime-vanagon-prep-project_5.5.x/puppet-runtime/configs/platforms/windowsfips-2012r2-x64.rb':
04:29:32 Platform not implemented for 'windowsfips-2012r2-x64' yet. Please go do so..
```
This PR adds `windowsfips` as a Windows-based platform.

(maint) add windowsfips as a windows platform

---

.github/workflows/ruby.yml

Github writes:
.github/workflows/ruby.yml#L1
Input 'version' has been deprecated with message: The version property
will not be supported after October 1, 2019. Use ruby-version instead

(maint) respond to 'version' deprecation notice from github

---

CHANGELOG.md
lib/vanagon/platform/deb.rb
lib/vanagon/platform/rpm.rb
lib/vanagon/platform/rpm/sles.rb
lib/vanagon/platform/solaris_10.rb
spec/lib/vanagon/platform/dsl_spec.rb

This commit adds the '--silent' '--show-error' and '--fail' flags to
calls made by vanagon to force bad fetches to return non-zero exit
status in the shell.
As a side-effect, some of the curl output statistics is silenced. I
think this silencing is desirable.
The previous behavior looked like this upon success:
$ curl -o STUFF https://artifactory.delivery.puppetlabs.net/artifactory/scratchpad__local/exg-test/foo.txt
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100    29  100    29    0     0    159      0 --:--:-- --:--:-- --:--:--   160
$ echo $?
0
The previous behavior looked like this upon  failure:
$ curl -o STUFF https://artifactory.delivery.puppetlabs.net/artifactory/scratchpad__local/exg-test/foo.txt.BAD …

(VANAGON-157) Make curl be more clear about fetch errors.

---

.rubocop.yml
CHANGELOG.md
lib/vanagon/platform.rb

~~This commit adds a utility matcher to determine whether the platform uses the system provided toolchain as opposed to pl-build-tools.~~
~~This is useful in the long term when adding new platforms to puppet-runtime and puppet-agent, because we avoid code duplication on building various C++ projects. It should also be future proof (except for when we are adding a new OS altogether).~~
Changed this PR to only add Ubuntu and Debian OS matchers. We'll rework the system toolchain/pl-build-tools issue inside puppet-runtime/puppet-agent.

(maint) Add Ubuntu and Debian utility matchers

---

CHANGELOG.md
lib/vanagon/component/source/rewrite.rb

* If there are no rewrite rules specified, don't do any processing on
the URI, just return it directly.
* If there are rewrite rules and the URI begins with `git:http` (to
specify a git source with an http url), substitute `git:http` with
`http` since fustigit gets rid of additional `/`. **Note** This will
result in deprecation warnings, and will break at some point in the
future.
* If there are rewrite rules and the URI doesn't begin with `git:http`,
keep existing behavior.

(VANAGON-159) Updates to `parse_and_rewrite` method

---

CHANGELOG.md
lib/vanagon/utilities.rb
spec/lib/vanagon/utilities_spec.rb

`find_program_on_path` needs to look for files with allowable extensions
when determining whether or not an executable exists.

(VANAGON-35) Update `find_program_on_path` to work on windows

---

CHANGELOG.md
lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb
lib/vanagon/project.rb
spec/lib/vanagon/component/rules_spec.rb
spec/lib/vanagon/platform/windows_spec.rb
spec/lib/vanagon/project/dsl_spec.rb
spec/lib/vanagon/project_spec.rb

This updates the `settings` hash to be initialized in the platform and
then copied to the project and components. This will allow the platform
to access the settings hash and set settings to be shared with the
project/component.

(VANAGON-72) Access `settings` hash from platforms

---

CHANGELOG.md
lib/vanagon/component/source/rewrite.rb

This wasn't added until Ruby 2.4 and vanagon supports back to 2.3.

(maint) Don't use `match?` method

---

.rubocop.yml
CHANGELOG.md
bin/repo

This will enable users to run `repo` when there are no rpm or deb
packages. This will be helpful in pipelines where you may only be
building for platforms without repositories.

(VANAGON-155) Add 'none' repo target to the repo binary

---

CHANGELOG.md
lib/vanagon/project.rb
lib/vanagon/project/dsl.rb
spec/lib/vanagon/platform/windows_spec.rb
spec/lib/vanagon/project/dsl_spec.rb
spec/lib/vanagon/project_spec.rb

Add ability to load upstream metadata when inheriting settings from other projects.

(VANAGON-144) Load metadata from upstream projects

---

CHANGELOG.md
Gemfile
lib/vanagon/project.rb

A variety of projects are very dependent on having minimal output to
stdout, so general practice with vanagon has been to print all
informative log messages to stderr to avoid breakages here.

(maint) Move info output to stderr

---

CHANGELOG.md
lib/vanagon/platform.rb
resources/rpm/project.spec.erb

The __debug_package macro handling on el8 suddenly broke. Not sure
why. This will hack around the problem until we understand it more.

(maint) el-8 __debug_package breakage

---

resources/rpm/project.spec.erb

this was causing collision errors

(maint) Build el-8 packages without build-id files

---

CHANGELOG.md
lib/vanagon/driver.rb
lib/vanagon/platform.rb
lib/vanagon/project.rb

We were previously regenerating the build_metadata when building
archives (i.e. for puppet-runtime). This change will make it so that
when we're writing the metadata out to the `ext` directory we also write
it out to the vanagon workdir so we have access to it on the build
host.
Prior to these changes, the build metadata file that landed in the
`output` directory contained invalid json. This fixes that issue.

(maint) Don't regenerate build metadata for archives

---

CHANGELOG.md
lib/vanagon/platform/deb.rb
lib/vanagon/platform/rpm.rb

This adds the `--location` tag to the curl call to follow any redirects.

(RE-13296) Follow redirects when installing rpm or deb repos

---

CHANGELOG.md
lib/vanagon/engine/docker.rb
lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb
spec/lib/vanagon/engine/docker_spec.rb

This changeset updates the Vanagon Docker image to allow the use of
`docker exec` and `docker cp` to be selected over `ssh` and `rsync`
by setting the `use_docker_exec` attribute to `true` in a
platform definition.
This change allows platform definitions to dispense with custom images
and SSH settings, which dramatically simplifies Docker configuration:
platform 'debian-10-amd64' do |plat|
plat.docker_image 'debian:10-slim'
plat.docker_run_args ['--tty', '--entrypoint=/bin/sh']
plat.use_docker_exec true
end

(VANAGON-100) Allow the use of docker exec instead of SSH

---

CHANGELOG.md
lib/vanagon/driver.rb

Vanagon has a bunch of logic for picking an engine based on the
configuration of the platform and other bits of info. This is
all well and good, but the logic was applied even when a user
had explicitly passed the `--engine` option to the CLI.
This patchset updates the Vanagon::Driver to skip the selection
logic when an engine has been explicitly chosen.
Additionally, error handling for engine loads is improved by
preserving the stack trace and original error message raise
instead of claiming all engine load failures are due to the
engine not existing.

(VANAGON-163) Fix engine selection

---

lib/vanagon/engine/docker.rb

This commit updates the logic in `Vanagon::Engine::Docker#cp_globs_from`
to match the behavior of `Vanagon::Utilities#rsync_from` by copying
directory contents instead of directories when both the source path
and target path are directories. E.g. `cp_globs_from('foo/', 'bar/')`
is treated as `cp_globs_from('foo/*', 'bar/')`, which matches the
behavior of `rsync -r`.

(VANAGON-100) Match rsync behavior in docker_cp_globs_from

---

CHANGELOG.md
Gemfile
README.md
lib/vanagon/engine/always_be_scheduling.rb
lib/vanagon/engine/pooler.rb
lib/vanagon/utilities.rb
spec/lib/vanagon/engine/always_be_scheduling_spec.rb
spec/lib/vanagon/engine/ec2_spec.rb
spec/lib/vanagon/engine/pooler_spec.rb
spec/spec_helper.rb

Before this change, the ABS engine was partially implemented.
It now includes the select_target and teardown methods needed for
vanagon build lifecycle.
This engine is thus a level of abstraction that supports any downstream
engine (vmpooler, nspooler, AWS) and is forward compatible with
ondemand Vmpooler pools.
The ABS token is read from env var ABS_TOKEN or the first line of ~/.vanagon-token
or the vmfloaty config (using top-level token or the first abs type service found)
The vmpooler token optionaly can be provided through an env var VMPOOLER_TOKEN
or the second line of ~/.vanagon-token or via vmfloaty's existing vmpooler_fallback config
The ABS request is done and checked for up to an hour, with feedback given on the
availability of resources. Teardown is done at the end using the …

(DIO-1066) Update vanagon to go through ABS for VMs

---

CHANGELOG.md
resources/osx/postinstall.erb
resources/solaris/10/postinstall.erb

Configuration files installed with `install_configfile` have the
`.pristine` extension appended to them, as a guard to avoid clobbering
existing configfiles.
OS X and Solaris 10 use postinstall scripts to manage configuration
files, removing the extension if a non-pristine config file does not
exist.
However, we don't need to keep the pristine files if there are no
differences between the pristine file and the target file. So, update
the logic to also run a `diff` between the two files. If there are no
differences, go ahead and override the target file.

(maint) Overwrite unchanged config files

---

CHANGELOG.md
lib/vanagon/cli/build.rb
lib/vanagon/driver.rb

After commit https://github.com/puppetlabs/vanagon/commit/ac44f694dfa68de71c6e4153e9bf35dc129bfca5 the options hash passed to
https://github.com/puppetlabs/vanagon/blob/94573411754397aa1efc47bbb09705f088835eb0/lib/vanagon/driver.rb#L23
was changed and now contains `:engine` key, making code at
https://github.com/puppetlabs/vanagon/blob/94573411754397aa1efc47bbb09705f088835eb0/lib/vanagon/driver.rb#L42-L44
to always load the engine, even if `target` option is also present
After this commit, the specified engine will be loaded only if target argument is missing.

(RE-13776) target argument handling

---

CHANGELOG.md
lib/vanagon/driver.rb

After default engine was changed to 'always_be_scheduling' target
argument was ignored

(maint) fix target argument handling

---

CHANGELOG.md
lib/vanagon/component/dsl.rb
lib/vanagon/project.rb
lib/vanagon/project/dsl.rb
resources/deb/control.erb
resources/rpm/project.spec.erb
spec/lib/vanagon/component/dsl_spec.rb

Added support for passing a version to `requires` in components and projects. Updated `get_requires` to handle the versions, and pass them to the rpm and deb packages. 

(VANAGON-129) Allow for passing version to 'requires'

---

CHANGELOG.md
resources/osx/postinstall.erb
resources/solaris/10/postinstall.erb

On Solaris 10, postinstall scripts are executed by the `sh` interpreter,
as the package manager does not seem to respect the shebang line at the
top of the file.
This causes the `!` sign to not be recognized, and the configfiles are
clobbered regardless of the differences between the installed config
file and the pristine config file.
Sample output after upgrading puppet-agent on Solaris 10:
```
/var/sadm/pkg/puppet-agent/install/postinstall: !: not found
/var/sadm/pkg/puppet-agent/install/postinstall: !: not found
/var/sadm/pkg/puppet-agent/install/postinstall: !: not found
/var/sadm/pkg/puppet-agent/install/postinstall: !: not found
/var/sadm/pkg/puppet-agent/install/postinstall: !: not found
/var/sadm/pkg/puppet-agent/install/postinstall: !: not found …
```

(maint) Fix pristine configfiles

---

CHANGELOG.md
resources/solaris/10/depend.erb
resources/solaris/11/p5m.erb

(VANAGON-164) Process the OpenStruct from `get_requires` in Solaris templates.

---

CHANGELOG.md

(maint) Prepping for 0.19.0 release.

---

CHANGELOG.md
lib/vanagon/component.rb

Resolves the following failure, allowing the actual underlying exception to be seen instead:
```
13:54:24 /var/lib/jenkins/workspace/platform_pdk_adhoc_pdk-van-init-manual-parameters_adhoc/pdk-vanagon/.bundle/gems/ruby/2.4.0/gems/vanagon-0.19.0/lib/vanagon/component.rb:144:in `rescue in load_component': undefined method `VanagonLogger' for Vanagon::Component:Class (NoMethodError)
13:54:24 	from /var/lib/jenkins/workspace/platform_pdk_adhoc_pdk-van-init-manual-parameters_adhoc/pdk-vanagon/.bundle/gems/ruby/2.4.0/gems/vanagon-0.19.0/lib/vanagon/component.rb:138:in `load_component'
13:54:24 	from /var/lib/jenkins/workspace/platform_pdk_adhoc_pdk-van-init-manual-parameters_adhoc/pdk-vanagon/.bundle/gems/ruby/2.4.0/gems/vanagon-0.19.0/lib/vanagon/project/dsl.rb:274:in `component'
13:54:24 …
```

(MAINT) Fix invalid invocation of VanagonLogger in Component class

---

CHANGELOG.md

(maint) Prepping for 0.19.1 release.

---

CHANGELOG.md
lib/vanagon/component/source/git.rb
spec/lib/vanagon/component/source/git_spec.rb
spec/lib/vanagon/utilities_spec.rb
vanagon.gemspec

Create a slightly sloppy workaround for a failure in Git.ls_remote
When Git.ls_remote calls the git command-line, under moderately common circumstances, ssh can be involved and it can print something like:
Warning: Permanently added 'github.com,192.30.255.113' (RSA) ...
Git.ls_remote, does not anticipate this and attempts to parse it as actual `git ls-remote` output.
This results in a `NoMethodError: undefined method 'split' for nil:NilClass` because the [#split](https://github.com/ruby-git/ruby-git/blob/bd026d39b17e192e8a710744153ed28139cc64a7/lib/git/lib.rb#L502) fails on the unexpected message.
I think that leaves us with 3 possible solutions.
1. Not use ruby-git for this operation (which was my choice).
1. monkey-patch the Git.ls_remote method (which was my 2nd choice)
1. catch the …

(RE-13837) Hack around Git.ls_remote failure

---

CHANGELOG.md
lib/vanagon/component.rb
lib/vanagon/component/dsl.rb
lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb
lib/vanagon/project.rb
resources/deb/postinst.erb
resources/deb/postrm.erb
resources/deb/prerm.erb
resources/rpm/project.spec.erb
spec/lib/vanagon/component/dsl_spec.rb
spec/lib/vanagon/platform_spec.rb

Debian in particular supports running modern systems under either
systemd or sysv. This adds support for passing multiple servicetypes in
your platform definition and also installing multiple services.
This PR contains the original changes from https://github.com/puppetlabs/vanagon/pull/556 with systemd check updated
to be the same as the one used by puppet systemd service provider

(VANAGON-123) deb systemv and systemd

---

lib/vanagon/component/dsl.rb
resources/deb/postinst.erb
resources/deb/prerm.erb

save `init_system` in OpenStruct since it is used later in scripts templates
without this change, postinstall actions are executed twice, ignoring init_system

(maint) keep `init_system` in OpenStruct

---

README.md
lib/vanagon/component.rb
spec/lib/vanagon/component_spec.rb

Previous the VANAGON_USE_MIRROR env variable only recoginzied `n`. This
seems counter intuitive, so I've added a small adjustment to have it
also recognize `false`.

(maint) Allow VANAGON_USE_MIRROR to recognize `false`

---

CHANGELOG.md
lib/vanagon/cli/ship.rb

When an artifact upload/ship fails, we want to see all the gory details so
that we can diagnose it.
This removes the polite message that masks the failures.

(RE-13838) Do not mask critical upload failures

---

CHANGELOG.md
lib/vanagon/platform/dsl.rb

(VANAGON-85) Add method to clear the provisioning command array

---

CHANGELOG.md
lib/vanagon/component.rb
lib/vanagon/component/source.rb
lib/vanagon/component/source/git.rb
spec/lib/vanagon/component/source/git_spec.rb

puppet-agent#6.x needs to ship both facter#3.x and
facter#main branches using 2 different components(
facter#3.x -> facter, facter#main -> facter-ng).
In order to do this, the component must configure
the directory where the git repository should be cloned.
This PR makes use of `dirname` attribute that can
be set at component level and exposes this to the
Git source in order to enable the ability to clone
and use a repository with a specific name.
Eg. of usage: https://github.com/puppetlabs/puppet-agent/pull/2075/files
```
pkg.load_from_json('configs/components/facter-ng.json')
pkg.dirname("facter-ng")
```

(PA-3570) enable clone into a custom dirname

---

CHANGELOG.md
README.md
lib/vanagon/cli/list.rb
spec/lib/vanagon/cli_spec.rb

(maint) Alphabetize vanagon list.

---

CHANGELOG.md
lib/vanagon/platform/osx.rb
lib/vanagon/platform/windows.rb
lib/vanagon/utilities.rb
lib/vanagon/utilities/extra_files_signer.rb
spec/lib/vanagon/utilities/extra_files_signer_spec.rb

- extract the generic code for signing extra files
- use the ExtraFilesSinger in osx and windows

(PA-3755) Add support for mac OS code signing

---

CHANGELOG.md
lib/vanagon/platform/defaults/el-8-aarch64.rb
lib/vanagon/platform/defaults/el-8-x86_64.rb

RedHat recently updated their repos and the cmake
version pulled is newer (3.18.2). This uses a
libarchive method that is not available on
3.3.2 which is the one that comes with the box.
Installing a newer version of libarchive fixes the
compliation issues with cmake 3.18.2

(maint) install `libarchive` on el-8

---

CHANGELOG.md
lib/vanagon/platform/osx.rb
lib/vanagon/utilities/extra_files_signer.rb
spec/lib/vanagon/utilities/extra_files_signer_spec.rb

`-E, --extended-attributes - copy extended attributes`
This flag is needed because the code signature is
stored as a xattr.

(PA-3755) add --extended-attributes on mac OS

---

CHANGELOG.md
README.md
lib/vanagon/utilities/extra_files_signer.rb
spec/lib/vanagon/utilities/extra_files_signer_spec.rb

By default, Vanagon does not fail if extra files signing fails, it just logs an error and continues building the package. This is unwanted behavior in environments where we expect a hard failure when signing cannot proceed.
To force Vanagon to fail if extra files signing fails, ensure the VANAGON_FORCE_SIGNING variable is set before starting a build.

(RE-14154) Exit if `VANAGON_FORCE_SIGNING` is set

---

CHANGELOG.md
lib/vanagon/platform.rb
resources/rpm/project.spec.erb

Because of the undefine statement openssl fails to start on RedHat 8
FIPS:
```
[root@nonacid-gel ~]# /opt/puppetlabs/puppet/bin/openssl
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
Aborted (core dumped)
```
After removing the statement openssl works:
```
[root@nonacid-gel ~]# /opt/puppetlabs/puppet/bin/openssl
OpenSSL>
```
I'm not sure what the statement does, I assume something related to
stripping libs/binaries, but whatever it is FIPS doesn't like it.

(VANAGON-166) Do not undefine __debug_package on EL 8 FIPS

---

CHANGELOG.md
resources/rpm/project.spec.erb

I was able to build puppet-agent and pe-r10k-vanagon RPMs on el-8-x86_64 without this workaround. Without more context it's hard to see how/why this might have failed. Remove the workaround and see what happens.
I rummaged through Slack and was able to locate the initial failure, which appeared during the pe-r10k RPM creation:
```
10:40:08 extracting debug info from /var/tmp/tmp.bkOcmruabx/rpmbuild/BUILDROOT/pe-r10k-3.4.1.1.14.gf7f4800-1.el8.x86_64/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/extensions/x86_64-linux/2.5.0/ffi-1.11.1/ffi_c.so
10:40:08 extracting debug info from /var/tmp/tmp.bkOcmruabx/rpmbuild/BUILDROOT/pe-r10k-3.4.1.1.14.gf7f4800-1.el8.x86_64/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/extensions/x86_64-linux/2.5.0/rugged-0.27.7/rugged/rugged.so
10:40:08 …
```

(VANAGON-177) Remove EL8 __debug_package workaround

---

CHANGELOG.md
lib/vanagon/platform/defaults/el-9-aarch64.rb
lib/vanagon/platform/defaults/el-9-x86_64.rb
resources/rpm/project.spec.erb

Add platforms to support building on el-9 based systems
In CentOS Stream 9
```
dnf install '/bin/mkdir'
Last metadata expiration check: 0:00:09 ago on Thu 02 Dec 2021 12:25:13 PM CET.
No match for argument: /bin/mkdir
Error: Unable to find a match: /bin/mkdir
```
where as
```
dnf install '/usr/bin/mkdir'
```
does install `coreutils-single`
Note that Fedora < 26 has already been deprecated and that case can be
ignored.

(VANAGON-174) Add el-9 definitions to vanagon

---

CHANGELOG.md
bin/repo
lib/vanagon/cli/ship.rb
lib/vanagon/cli/sign.rb

Reverts puppetlabs/vanagon#725
Puppet Agent and components have packaging location pinned to 0.99.43 but pull from vanagon main branch. This depends on changes in packaging 0.105.0. Reverting this to un-break their pipelines, and the updates to those projects will be ticketed for after the upcoming releases

Revert "VANAGON-165"

---

lib/vanagon/engine/always_be_scheduling.rb

Before this change ABS requests were made at priority 1 and the job ID would look like: `unknown-1642527707`
This change lowers the priority to 3 and makes the job id more identifiable

(maint) Use Priority 3 ABS requests, identifiable user / job name

---

.github/workflows/ruby3.yml
.travis.yml
CHANGELOG.md
Gemfile
lib/git/basic_submodules.rb
lib/vanagon/component.rb
spec/lib/vanagon/engine/ec2_spec.rb
vanagon.gemspec

Allow vanagon to be run with ruby 3. In particular CentOS stream 9
is ruby 3.0.2p107.
Closes #722

(VANAGON-179) Support ruby 3 for vanagon localhost

---

CHANGELOG.md
lib/vanagon/platform/osx.rb
resources/Makefile.erb

(RE-13380) Support Apple Notarization for Puppet Packages.

---

CHANGELOG.md
lib/vanagon/component/source/git.rb

(VANAGON-187) Change valid remote repository check to use 'git ls-remote --heads'

---

CHANGELOG.md
lib/vanagon/platform/osx.rb
resources/Makefile.erb

This reverts commit 5919ba23749dbc5fa4674dac75ef418687ebd882.
The Phoenix team has had issues with the new Apple signing/notarization process and have had to pin to f0f43db (the commit prior to notarization being added).
To move forward with other Vanagon changes (e.g. adding macOS 12 support) we'll need to revert notarization changes.

Revert "(RE-13380) Support Apple Notarization for Puppet Packages."

---

spec/lib/vanagon/component/source/git_spec.rb
spec/lib/vanagon/component/source_spec.rb
spec/lib/vanagon/component_spec.rb

(VANAGON-192) Add allow net connect in #force_version spec test to fix failing tests with https.

---

lib/vanagon/component/source/local.rb

Currently, the logic for decompressing .tar.xz archives uses `unxz`
which pipes to `tar`. This uses multiple tools unnecessarily and
doesn't work.
This commit simplifies the logic to only use `tar`.
Encountered issues with this while downloading the latest archive dmidecode for PA-4423.
Tested this behavior on a RedHat 7 machine:
```
[root@indirect-door ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)
[root@indirect-door test]# curl http://download.savannah.gnu.org/releases/dmidecode/dmidecode-3.3.tar.xz -JLOs; unxz -d "dmidecode-3.3.tar.xz" | tar xvf -; ls; rm -rf dmidecode*
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
dmidecode-3.3.tar
[root@indirect-door test]# curl …
```

(maint) Simplifies logic for .tar.xz archives

---

CHANGELOG.md
resources/deb/rules.erb

(maint) force dh_builddeb to use -Zgzip for reprepro compatibility

---

CHANGELOG.md
lib/vanagon/platform/deb.rb

Set compat to '10' which is the lowest still supported.

(maint) compat levels below 10 are deprecated

---

CHANGELOG.md
lib/vanagon/platform.rb

When one provides a non-existent platform, provide a kinder error message without the stacktrace.
Relax requirement that the platform name not contain the '.rb' extension.

(maint) Gentler fail when platform file isn't found.

---

CHANGELOG.md
resources/osx/project-installer.xml.erb

This change allows the install of the puppet-agent package on macos M1

(maint) Seeing if setting host arch to be x86_64,arm64 will work

---

CHANGELOG.md
lib/vanagon/platform/defaults/fedora-36-x86_64.rb

(VANAGON-193) Adds support for Fedora 36 (x86-64)

---

CHANGELOG.md
lib/vanagon/utilities/extra_files_signer.rb
spec/lib/vanagon/utilities/extra_files_signer_spec.rb

(maint) Revert extra file signing to use rsync again instead of scp due to issues with macos.

---

CHANGELOG.md
lib/vanagon/platform/defaults/osx-10.15-x86_64.rb

Homebrew has removed the ability to be installed via ruby, so this PR changes to the bash method the other newer versions of MacOS use.

(maint) osx-10.15 installs Homebrew via the bash method

---

CHANGELOG.md
lib/vanagon/component/source/git.rb

Exempt github URLs from being checked as valid git repositories in
order to avoid rate-limiting from excessive traffic.

(RE-15209) Exempt github URLs from validation checking

---

CHANGELOG.md
lib/vanagon/platform/defaults/el-8-ppc64le.rb
lib/vanagon/platform/defaults/redhatfips-7-x86_64.rb
lib/vanagon/platform/defaults/redhatfips-8-x86_64.rb

I was able to build puppet-runtime packages containing Ruby 3.2 on these platforms:

(PA-4838) Update platform defaults for RHEL 8 ppc64le, RHEL 7 & 8 FIPS

---

CHANGELOG.md
lib/vanagon/platform/defaults/ubuntu-18.04-aarch64.rb

This commit merges the packages formerly from the Ubuntu 18.04 aarch64/ARM64 platform definition in puppet-runtime with the Vanagon defaults and adds autoconf to enable building Ruby 3.2.

(PA-4841) Combine Ubuntu 18.04 aarch64 packages

---

CHANGELOG.md
lib/vanagon/engine/base.rb
lib/vanagon/engine/docker.rb
spec/lib/vanagon/engine/pooler_spec.rb

This allows the CLI target argument to override the target user and port
specified in the platform config. This is useful for local dev
environments that don't match the enviroment used in the real build
pipeline. Previously, this required temporarily modifying the platform
config, which is more onerous than simply passing the argument on the
CLI.

(maint) Allow target on CLI to set user and port

---

CHANGELOG.md
resources/Makefile.erb

Cygwin supports four different forms of Windows paths:
* short: C:/PROGRA\~1 or C:\\PROGRA~1
* windows: "C:\\Program Files"
* unix: /cygdrive/c/Program\ Files
* mixed: "C:/Program Files"
Previously, we ran `find` across a set of root paths and then converted each file using `cygpath` to its "mixed" form. This is surprising slow on Windows, taking 10 minutes.
This commit switches the order so that we normalize the root paths first and then run `find`. The `find` command preserves the "mixed" form, so it doesn't need to be normalized again. This change reduces the time to generate the list from 10 minutes to 2-3 seconds:
Before https://jenkins-platform.delivery.puppetlabs.net/view/puppet-runtime/view/agent-runtime-7.x/job/platform_agent-runtime_runtime-vanagon-packaging_7.x/BUILD_TARGET=wind …

(VANAGON-211) Run cygpath before find

---

CHANGELOG.md
lib/vanagon/platform/defaults/osx-10.15-x86_64.rb
lib/vanagon/platform/defaults/osx-11-arm64.rb
lib/vanagon/platform/defaults/osx-11-x86_64.rb
lib/vanagon/platform/defaults/osx-12-arm64.rb
lib/vanagon/platform/defaults/osx-12-x86_64.rb

* Create `test` home directory before installing brew (since brew expects the home directory to be writable, especially `~/Library/Logs`)
* Opt out of homebrew analytics (from puppet-agent)
* Add platform definition for macOS 11 & 12 ARM64 (from puppet-agent)
* Fix incorrect changelog for VANAGON-211
I'm going to skip the last two because I'm pretty sure they work and we'll need to merge up puppet-agent#6.x -> 7.x -> main
I also manually tested pdk-runtime and bolt-runtime with 10.15.

(VANAGON-214) Create `test` home directory before installing brew

---

CHANGELOG.md
lib/vanagon/platform/deb.rb

(maint) Name file in deb build 'buildinfo' instead of 'build' to make signing work with newer versions of debsign.

---

CHANGELOG.md

Also tightened up some of the line-spacing in the Changelog.

(maint) Prep for 0.36.0 release

---

.rubocop.yml
CHANGELOG.md
lib/vanagon/component/source.rb
lib/vanagon/component/source/git.rb
spec/lib/vanagon/component/source/git_spec.rb
spec/lib/vanagon/component/source_spec.rb

A https://github.com URL prefix does not guarantee that the resolved URL is
an actual git repository. Many github URLs are download API calls (like
'archive', 'zipball', 'tarball'). Start recognizing them and make
allowances for future options.

(VANAGON-227) Try to be smarter about identifying github repositories

---

lib/vanagon/utilities.rb

In Ruby >= 3.0, keyword arguments are separated from positional arguments:
https://bugs.ruby-lang.org/issues/14183
This commit updates method calls that passes a keyword argument as the last argument to separate out those keyword arguments.

(maint) Use keyword arguments

---

CHANGELOG.md

A vanagon release needs to be cut with the commit in PR #805 so Windows vanagon builds stop failing due to TLS.

(maint) Update CHANGELOG for 0.37.1 release

---

CHANGELOG.md
lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb
lib/vanagon/platform/osx.rb

In 2020, Apple began releasing machines that used new ARM-based  processors, as opposed to the x86 processors it had used for many years prior.
Homebrew, a macOS package manager, changes its path depending on whether it's running on x86-64 or ARM64.
This commit adds a new `brew` method to Vanagon that defaults to the x86 path (/usr/local/bin/brew) but can be overriden to the ARM path (/opt/homebrew/bin/brew).

(maint) Add brew method for macOS

---

CHANGELOG.md
lib/vanagon/platform/dsl.rb

The puppet-runtime repo needs to build agent-runtime-7.x and agent-runtime-main projects using different solaris 11 sparc platform definitions, one is cross-compiled, the other is not. It's not possible to have conditional logic in the platform definition, because the platform DSL is evaluated before the project DSL[1].
In addition, the platform definition's filename is used to name the build artifacts, for example note solaris-113 in:
agent-runtime-main-202308020.2.g2ddb502.solaris-113-sparc.tar.gz
However, this breaks vanagon projects that try to consume that tarball, like pxp-agent-vanagon and puppet-agent.
Therefore, this modifies vanagon so that it's possible to override the platform name, version or architecture, different than the platform definition's filename, for example: …

(PA-5701) Allow platform's name to be overridden

---

CHANGELOG.md
lib/vanagon/component/source/git.rb
lib/vanagon/component/source/http.rb
spec/lib/vanagon/component/source/git_spec.rb

Previously, this was attempting to determine if a github.com URL was a remote or a media type by inspecting part of the path. However, this was missing paths with 'release' in them. Also, we were never actually using any other return type but :github_remote. This changes the logic to return :github_media if the path contains known media tokens, or if the suffix ends with .tar.gz or .zip. Otherwise, we assume it's a remote.
Ideally, we'd reach out to GitHub to determine if it's a repo, but we're doing this to avoid rate limiting.
Because the 'request' function does NOT return the value the block you pass it returns, this function was always returning a Net::HTTP object. With how this function was being used, it would result in valid_url? always being truthy.  Net::HTTP.start DOES return …

Fix git detection

---

CHANGELOG.md
lib/vanagon/project.rb
vanagon.gemspec

This allows us to remove the yaml_safe_load_shim hack and treat
safe_load consistently.

(maint) Force >= 4.0 of psych gem

---

CHANGELOG.md
lib/vanagon/component.rb
lib/vanagon/component/dsl.rb
lib/vanagon/project.rb
resources/rpm/project.spec.erb

The existing `#add_postinstall_action` adds actions to the `%posttrans` section of an rpm spec file. This can mean that the action could fail, but the installation/upgrade could still succeed. This commit adds the ability to add actions that must succeed post installation for rpm installations by adding the action to the `%post` section.

(PA-5786) Add ability to execute direct post installation scriptlets

---

CHANGELOG.md

Also cleaned up some header inconsistency in the CHANGELOG by removing redundant &
conflicting '- release', '- released', and '- released on' strings.

(maint) Prep for 0.40.0 release

---

lib/vanagon/component.rb
lib/vanagon/component/dsl.rb
lib/vanagon/project.rb
resources/rpm/project.spec.erb

This reverts commit 93ba1b4ee3d7b5f15951b2a6eee0043faa16dc06.

Revert "(PA-5786) Add ability to execute direct post installation scriptlets"

---

CHANGELOG.md
lib/vanagon/component.rb
lib/vanagon/component/dsl.rb
lib/vanagon/project.rb
resources/rpm/project.spec.erb

The existing `#add_postinstall_action` adds actions to the `%posttrans` section of an rpm spec file. This can mean that the action could fail, but the installation/upgrade could still succeed. This commit adds the ability to add actions that must succeed post installation for rpm installations by adding the action to the `%post` section.
A previous attempt to add this was done in 93ba1b4; that introduced a bug where the install and upgrade files were incorrectly deleted after the %post step. They needed to remain so that the %posttrans rpm section would detect the install/upgrade via vanagon's

(PA-5786) Add ability to execute direct post installation scripts

---

CHANGELOG.md
lib/vanagon/component/source/git.rb

Vanagon::Component::Source::Git will throw an error message during
initialization if it thinks that the passed url is invalid.
Make a change to the error message to specify which url it was
reporting as invalid.

(VANAGON-235) Specify which URL is invalid

---

lib/vanagon/platform.rb
resources/rpm/project.spec.erb

Added condition for Amazon Linux in project.spec.erb

(PA-5947) Added condition for Amazon Linux in project.spec.erb

---

.github/workflows/ruby.yml
.rubocop.yml
lib/vanagon/platform.rb

ruby 2.7 is compatible with <= bundler 2.4.22. Latest version of bundler is causing failures in checks.

(vanagon-238) Fix rubocop offence and workflow issue

---

CHANGELOG.md
lib/vanagon/component/source.rb
lib/vanagon/component/source/git.rb
lib/vanagon/component/source/rewrite.rb
spec/lib/vanagon/project_spec.rb
vanagon.gemspec

build-uri provides similar functionality as fustigit without the monkey-patching
Also update related specs with some additional light housecleaning in the spec.

(RE-16095) Abandon fustigit in favor of build-uri.

---

CHANGELOG.md

(maint) prep for 0.46.0 release

---

CHANGELOG.md
lib/vanagon/platform/defaults/el-9-ppc64le.rb

(PA-5323) Added changelog
To get `swig` installed I have added: `--enable codeready-builder-for-rhel-9-ppc64le-rpms`

(PA-5323) Add RedHat 9 (Power9) platform definition to vanagon

---

CHANGELOG.md
lib/vanagon/engine/docker.rb
spec/lib/vanagon/engine/docker_spec.rb

The select_target method was broken because URI.new is not a valid method.

Use URI.parse when selecting the docker target

---

CHANGELOG.md
lib/vanagon/platform/defaults/amazon-7-aarch64.rb

(VANAGON-242) Add Amazon Linux2 ARM platform definition to vanagon

---

CHANGELOG.md
lib/vanagon/platform/defaults/ubuntu-24.04-aarch64.rb

(VANAGON-243) Add Ubuntu 24.04 (ARM) platform definition to vanagon

---

CHANGELOG.md
lib/vanagon/platform/defaults/amazon-2-aarch64.rb

We're intentionally continuing to use the amazon-7-arm64 VM template
Successfully built puppet-runtime https://builds.delivery.puppetlabs.net/puppet-runtime/d743d36f9d92d18abc43cce9f35d2328b5a6c1f5/repos/agent-runtime-main-202308240.260.gd743d36.amazon-2-aarch64.tar.gz

Copy amazon-7 to amazon-2
