puppetlabs/vanagon

.rubocop.yml
lib/vanagon/component/source.rb
lib/vanagon/engine/pooler.rb
lib/vanagon/platform/deb.rb
lib/vanagon/platform/dsl.rb
lib/vanagon/platform/rpm.rb
lib/vanagon/platform/rpm/aix.rb
lib/vanagon/platform/rpm/sles.rb
lib/vanagon/utilities.rb
spec/lib/vanagon/engine/pooler_spec.rb
spec/lib/vanagon/platform/dsl_spec.rb
spec/lib/vanagon/platform/rpm/aix_spec.rb
spec/lib/vanagon/platform/rpm_spec.rb

This PR refactors 4 problematic methods that were triggering PerceivedComplexity[1] cops. The methods in question were deeply nested with a lot of conditional logic. The refactors took a few paths to alleviate this: removing unneeded conditionals and refactoring behavior into smaller methods. Some of the refactoring included adding new subclasses for AIX and SLES. The final commit reenables the PerceivedComplexity cop in vanagon.
[1] - http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Metrics/PerceivedComplexity

(RE-5565) Resolve PerceivedComplexity rubocop violations for more maintainable code

---

README.md

We want to encourage people to file issues on our project and discuss
issues on #puppet-dev

(maint) Add support information to the readme

---

lib/vanagon/platform/windows.rb

Ticket/vanagon for the win/re 5976 install chocolatey
Initial ticket for discussion.

(RE-5976) - Install Chocolatey as part of Windows/Vanagon bootstrap

---

lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb
templates/rpm/project.spec.erb

Platform has changed from RPM to DEB.

(maint) Update HuaweiOS to use deb packaging

---

Gemfile
README.md
lib/vanagon/driver.rb
lib/vanagon/engine/hardware.rb
lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb
spec/lib/vanagon/engine/hardware_spec.rb
vanagon.gemspec

Read the commit messages now. They are very detailed and kept updated as this is reviewed. But, here's a picture.

Add Hardware engine to vanagon

---

lib/vanagon/component/dsl.rb
lib/vanagon/platform/windows.rb

Outline package definition scripts for MSI generation.
First push up for discussion purposes only.

(RE-5863) - Teach Vanagon harvest files for Wix

---

lib/vanagon/platform/windows.rb

It's unnecessary and adds to the number of characters I have to type

(maint) Remove project subdirectory

---

lib/vanagon/platform/windows.rb

Add Candle.exe (Wix Compiler) commands to generate_msi_package for Vanagon

(RE-6468) Add Candle.exe to Wix/Vanagon

---

lib/vanagon/platform/windows.rb

Initial PR to create the MSI
Needs #280 Merged first

(WIP) (RE-5685) Use light.exe to generate MSI

---

resources/windows/wix/registryEntries.wxs.erb

Directory tag on line 13 should be DirectoryRef

(MAINT) Fix Directory/DirectoryRef tag error

---

resources/windows/wix/project.wxs.erb
resources/windows/wix/registryEntries.wxs.erb

This commit updates the project and registryEntries wxs files in
order to alleviate some compiler errors.
Specifically:
* replace the ComponentGroupRef element with just a new
ComponentGroup.
* to facilitate the above, add a new componentGroupRef to the
project.wxs
* remove directoryRef, and replace it with the Directory attribute
inside the component element

(maint) update project and registryEntries wxs

---

lib/vanagon/component/dsl.rb
resources/windows/wix/project.wxs.erb

Using Group References as per:
http://stackoverflow.com/questions/7978066/how-to-include-fragments-in-wix
This requires Puppet-Agent PR https://github.com/puppetlabs/puppet-agent/pull/559 to be merged.

(RE-6464) Force inclusion of Custom Actions

---

lib/vanagon/platform/windows.rb
resources/windows/wix/directorylist.wxs.erb
resources/windows/wix/filter.xslt.erb
resources/windows/wix/project.wxs.erb
spec/lib/vanagon/platform/windows_spec.rb

This updated DirectoryList and the heat commands to create the correct directory structure in the PA MSI

Directorylist fixes

---

lib/vanagon/platform/windows.rb

Files were being installed in C:\ProgramData\PuppetLabs\PuppetLabs
Move files up one level to C:\ProgramData\PuppetLabs

(MAINT) Fix the CommonAppData location

---

lib/vanagon/platform/deb.rb

This reverts commit 9b90e4cfcb84367a9178cada383740cc504440a5, reversing
changes made to 256fc14a9108fb7a4c4ec0c809092c8011b9da55.
Options break Debian < 8

Revert "Merge pull request #322 from ScottGarman/deb-pkg-cross-builds"

---

lib/vanagon/platform/windows.rb

This is a copy of the bill-of-materials file which is placed into:
C:\Program Files\Puppet Labs\Puppet\misc

(RE-6506) Drop versions.txt into misc directory

---

lib/vanagon/project.rb

Running this through CI before I mark it as ready for merge.

(RE-6882) fix generation of package conflicts

---

lib/vanagon/component/source.rb
lib/vanagon/component/source/local.rb
spec/lib/vanagon/component/source/localsource_spec.rb
spec/lib/vanagon/component/source_spec.rb

Source::LocalSource is inconsistent with the rest of
the source children names, update this to just be
Source:Local as that's consistent with Source:http and the
like

(maint) update the LocalSource name

---

lib/vanagon/driver.rb

This commit adds engine loading helper
methods in order to facilitate a cleaner
and less complex driver init

(maint) add load_engine helper methods

---

lib/vanagon/component/source/http.rb

Otherwise we're liable to get a lot of 404s based on something as
trivial as character case.

(MAINT) Allow Vanagon to follow HTTP redirects

---

Gemfile
README.md
lib/vanagon/driver.rb
lib/vanagon/engine/ec2.rb
lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb

This is some initial work to use aws with vanagon. I am expecting some review of what else needs be done and some feedback.

(PA-341) Add AWS/EC2 engine to Vanagon

---

DESIGN.md

This is an incomplete doc only containing the docs for the windows platform,
more docs are to come.

(maint) Add the vanagon design doc to vanagon

---

README.md

We want to cut a new release, and that means updating the documentation. In addition to adding doc for the `inspect` command and the `RETRY_COUNT` environment variables, this PR includes a couple of formatting changes and some revised descriptions for common Vanagon activities. Please view it as a rendered document and make sure that nothing looks funky.

(MAINT) README updates!

---

docs/USING_VANAGON.md

I've updated the link to WIX examples to actually take you to . . . WIX examples.

Link to WIX Examples was Broken

---

CHANGELOG.md

It's a big PR, so it gets kind-of-a-big CHANGELOG entry

(MAINT) Update CHANGELOG for PR #394

---

lib/vanagon/component/source/git.rb
lib/vanagon/component/source/local.rb
spec/lib/vanagon/component/source/git_spec.rb
spec/lib/vanagon/component/source/local_spec.rb

This PR addresses the problem with vanagon's local source where it cannot handle nested directories. It also contains a feature which allows a user to specify what type of source to use when building a component.

(VANAGON-15) Allow directories when using local source

---

.rubocop.yml
Gemfile
Rakefile
lib/vanagon/engine/pooler.rb
vanagon.gemspec

New for 2017: a Rakefile that provides useful utilities for package maintainers, slightly improved linting, and a little bit of de/recomposition around the recently expanded vmpooler token support.

New year, same Vanagon

---

MAINTAINERS

Congratulations on your promotion, Mike.

(MAINT) Remove Mike Stahnke as maintainer

---

.rubocop.yml
Rakefile
lib/makefile.rb
lib/vanagon/component.rb
lib/vanagon/component/dsl.rb
lib/vanagon/component/rules.rb
lib/vanagon/component/source/local.rb
lib/vanagon/environment.rb
lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb
lib/vanagon/project.rb
lib/vanagon/project/dsl.rb
lib/vanagon/utilities.rb
resources/Makefile.erb
spec/lib/makefile_spec.rb
spec/lib/vanagon/component/dsl_spec.rb
spec/lib/vanagon/component/rules_spec.rb
spec/lib/vanagon/component_spec.rb
spec/lib/vanagon/environment_spec.rb
spec/spec_helper.rb
vanagon.gemspec

I'm trying something a little different for this feature addition... a "@rick used to work at github" style checklist and a longish-lived PR allowing others to track the status of a feature as it's developed.

(VANAGON-40) Environmental Activism

---

README.md
bin/build
lib/vanagon/component/dsl.rb
lib/vanagon/driver.rb
lib/vanagon/engine/always_be_scheduling.rb
lib/vanagon/engine/base.rb
lib/vanagon/engine/docker.rb
lib/vanagon/engine/ec2.rb
lib/vanagon/engine/hardware.rb
lib/vanagon/engine/local.rb
lib/vanagon/engine/pooler.rb
lib/vanagon/optparse.rb
lib/vanagon/platform.rb
lib/vanagon/platform/dsl.rb
lib/vanagon/platform/rpm.rb
resources/Makefile.erb
resources/rpm/project.spec.erb
spec/lib/vanagon/component/dsl_spec.rb
spec/lib/vanagon/driver_spec.rb
spec/lib/vanagon/platform/rpm_spec.rb
spec/lib/vanagon/platform/windows_spec.rb

Pulling in --remote-dir from 0.10.0 and config file options. Would like to also get https://github.com/puppetlabs/vanagon/pull/457 in before this gets merged.

Cherry-picks for 0.9.x

---

lib/vanagon/platform/dsl.rb

Cherry-picking leads to lots of duplicate commits, but better to get this merged up since we're doing a release.

Merge 0.9.x into master

---

CHANGELOG.md

Anything else that should get into this release?

(VANAGON-55) Update CHANGELOG for Vanagon 0.11.3

---

README.md

Let's just settle this one for all time.

(MAINT) Add a pronunciation guide

---

CHANGELOG.md

Updates changelog for 0.13.0 release of vanagon

(VANAGON-64) Update changelog for 0.13.0

---

.gitignore
Gemfile
lib/vanagon/component.rb
lib/vanagon/component/dsl.rb
lib/vanagon/platform/deb.rb
lib/vanagon/platform/osx.rb
lib/vanagon/platform/rpm.rb
lib/vanagon/platform/solaris_10.rb
lib/vanagon/platform/solaris_11.rb
lib/vanagon/platform/windows.rb
lib/vanagon/project.rb
resources/deb/postinst.erb
resources/deb/triggers.erb
resources/rpm/project.spec.erb
spec/lib/vanagon/component/dsl_spec.rb
spec/lib/vanagon/project_spec.rb

Adding support for triggers in Vanagon

(VANAGON-59) Add support for RPM and Debian Triggers

---

lib/vanagon/driver.rb
lib/vanagon/optparse.rb
spec/lib/vanagon/optparse_spec.rb

I'm bummed about the statefulness of the parser module but needed to preserve it for backward compatibility. Needed the full refactor for flexibility.

VANAGON-76 implement more flexible preserve

---

lib/vanagon/platform.rb

Updated to the standard documented in VANAGON-98.

(VANAGON-111) Update to standardized archive names

---

.gitignore
.yardopts
Rakefile
lib/vanagon.rb
lib/vanagon/common/pathname.rb
lib/vanagon/engine/always_be_scheduling.rb
lib/vanagon/environment.rb
lib/vanagon/extensions/hashable.rb
lib/vanagon/platform.rb
lib/vanagon/platform/rpm/aix.rb
lib/vanagon/platform/rpm/sles.rb
lib/vanagon/platform/rpm/wrl.rb
lib/vanagon/platform/windows.rb

This is mostly to make the docs that yard generates look better and be more legible.

A bunch of minor updates for yard

---

.rubocop.yml
Gemfile
bin/build
bin/build_host_info
bin/inspect
bin/render
bin/ship
lib/vanagon.rb
lib/vanagon/component.rb
lib/vanagon/component/dsl.rb
lib/vanagon/component/source/git.rb
lib/vanagon/component/source/http.rb
lib/vanagon/component/source/local.rb
lib/vanagon/driver.rb
lib/vanagon/engine/docker.rb
lib/vanagon/engine/ec2.rb
lib/vanagon/engine/hardware.rb
lib/vanagon/engine/pooler.rb
lib/vanagon/environment.rb
lib/vanagon/platform.rb
lib/vanagon/platform/rpm.rb
lib/vanagon/project.rb
lib/vanagon/project/dsl.rb
lib/vanagon/utilities.rb

I'm sick, so you know what that means: I'm touching your code again. Before I finish the Docker work I started back in, like June, I thought I'd update Rubocop and let it catch any egregious mess-ups I might make. Here's the needful to make that happen.

Update Rubocop to 0.52.1

---

CHANGELOG.md

If someone could double check that i categorized things the right way that'd be awesome

(maint) Changelog for 0.15.7 release

---

CHANGELOG.md

@scotje let us know if your build works, and we can get this released!

(maint) 0.15.19 prep

---

.github/workflows/release.yml

Was able to confirm this works.

(maint) Update gem publish trigger

---

lib/vanagon/platform.rb

Change the is_windows? method to match also windowsfips

(maint) match windowsfips under is_windows?

---

CHANGELOG.md

(RE-12849) Prep changelog for 0.15.30 release

---

CHANGELOG.md

(maint) Prep for 0.15.32 release

---

.rubocop.yml
CHANGELOG.md
lib/vanagon/project/dsl.rb

(VANAGON-112) Fix undefined variable in error messages

---

lib/vanagon/component/dsl.rb
lib/vanagon/component/source.rb
lib/vanagon/component/source/git.rb
spec/lib/vanagon/component/dsl_spec.rb
spec/lib/vanagon/component/source/git_spec.rb

Adding support for --branch or other options in Git clone

VANAGON-161 Including support to clone options

---

CHANGELOG.md

(maint) changelog updates for 0.15.33

---

CHANGELOG.md

(maint) Prepare for 0.15.35 release

---

CHANGELOG.md

(maint) Prep for 0.15.36 release

---

CHANGELOG.md

(maint) update changelog for 0.15.37 release

---

CHANGELOG.md

Prep for 0.15.38 release

---

CHANGELOG.md

(maint) 0.16.0 release preparation

---

CHANGELOG.md
lib/vanagon/cli/ship.rb

(maint) Fix an issue where 'ship' command was failing

---

README.md

(maint) Update README.md to reflect CLI changes.

---

CHANGELOG.md

(maint) prepare for 0.17.0 release

---

CHANGELOG.md
lib/vanagon/cli.rb
lib/vanagon/cli/list.rb
spec/lib/vanagon/cli_spec.rb

(maint) Add list command

---

CHANGELOG.md
extras/completions/vanagon.bash
extras/completions/vanagon.zsh
lib/vanagon/cli.rb
lib/vanagon/cli/completion.rb
lib/vanagon/cli/list.rb
spec/lib/vanagon/cli_spec.rb
vanagon.gemspec

(maint) Add tab completion scripts for zsh and bash. Add vanagon completion command. 

---

CHANGELOG.md
lib/vanagon/cli/build.rb
lib/vanagon/cli/build_host_info.rb
lib/vanagon/cli/build_requirements.rb
lib/vanagon/cli/inspect.rb
lib/vanagon/cli/render.rb
lib/vanagon/driver.rb
spec/lib/vanagon/driver_spec.rb

Move default engine to 'always_be_scheduling'

---

CHANGELOG.md

Preparing for release.

---

CHANGELOG.md

(maint) prepare for 0.18.1 release

---

CHANGELOG.md
lib/vanagon/driver.rb

My first try at isolating the pick_engine method was buggy. Cas provided
us a better one.

(maint) Fix #pick_engine method

---

CHANGELOG.md

(maint) Preparing for 0.20.0 release.

---

CHANGELOG.md

(main) Preparing for 0.21.0 release.

---

CHANGELOG.md
lib/vanagon/platform/defaults/osx-11-x86_64.rb

(PA-3613) Add vanagon support for Big Sur

---

CHANGELOG.md
lib/vanagon/platform/defaults/fedora-34-x86_64.rb

(PA-3604) Add fedora34 to vanagon platform defaults

---

CHANGELOG.md

(maint) Preparing for 0.21.1 release.

---

CHANGELOG.md
lib/vanagon/engine/pooler.rb

(maint) Update nnspooler URL

---

CHANGELOG.md

(maint) prepare for 0.22.0 release

---

CHANGELOG.md
lib/vanagon/engine/pooler.rb

(maint) Update vmpooler URL

---

CHANGELOG.md

(maint) prep for 0.23.0 release

---

CHANGELOG.md
lib/vanagon/cli.rb
lib/vanagon/cli/dependencies.rb
lib/vanagon/driver.rb
lib/vanagon/project.rb

Command generates gem dependencies in json files for given projects and platforms in the tmp folder.

(RE-14305) Add 'vanagon dependencies' command

---

CHANGELOG.md
lib/vanagon/component/source/git.rb

This 'log_url' only shows the host/path.

(VANAGON-162) Added new instance variable 'log_url' to use in logs rather than the full git url

---

CHANGELOG.md
bin/repo
lib/vanagon/cli/ship.rb
lib/vanagon/cli/sign.rb

VANAGON-165

---

CHANGELOG.md

(maint) prep for 0.24.0 release

---

CHANGELOG.md

(maint) Update changelog for 0.25.0 release

---

CHANGELOG.md

(maint) Update changelog for 0.26.0 release

---

CHANGELOG.md
lib/vanagon/platform/defaults/osx-12-x86_64.rb

(VANAGON-181) Adds support for macOS 12 Monterey

---

CHANGELOG.md

Update changelog for 0.26.1 release

---

CHANGELOG.md
lib/vanagon/platform/defaults/ubuntu-20.04-amd64.rb

(maint) Add the focal-updates.list file creation and gpg key add to the provisioning step in the defaults for ubuntu-20.04-amd64

---

CHANGELOG.md

(maint) Update changelog for 0.26.2 release

---

CHANGELOG.md

(maint) Update changelog for 0.26.3 release.

---

CHANGELOG.md
lib/vanagon/platform/defaults/ubuntu-22.04-aarch64.rb
lib/vanagon/platform/defaults/ubuntu-22.04-amd64.rb

(VANAGON-182) Add Ubuntu 22.04

---

CHANGELOG.md

(maint) Preparing for 0.28.0 release

---

CHANGELOG.md
lib/vanagon/utilities/extra_files_signer.rb
spec/lib/vanagon/utilities/extra_files_signer_spec.rb

(maint) Update extra file sigining to accommodate new windows extra file signing. 

---

CHANGELOG.md
lib/vanagon/utilities/extra_files_signer.rb

(maint) Prep for 0.29.0 release.

---

lib/vanagon/utilities/extra_files_signer.rb

(maint) Remove unneeded log statements.

---

spec/lib/vanagon/utilities/extra_files_signer_spec.rb

(maint) Fix spec tests for extra file signer.

---

CHANGELOG.md
lib/vanagon/cli/build.rb
spec/lib/vanagon/engine/always_be_scheduling_spec.rb
spec/lib/vanagon/utilities/extra_files_signer_spec.rb

And fixed some unit test failures locally.

Fix `--only-build`

---

.github/workflows/ruby.yml
.github/workflows/ruby3.yml
CHANGELOG.md
vanagon.gemspec

(RE-15095) Update git gem from 1.11.0 to 1.13.0

---

CHANGELOG.md

(maint) Update CHANGELOG for 0.32.0 release.

---

CHANGELOG.md

(maint) Update CHANGELOG for 0.33.0 release.

---

CHANGELOG.md

(maint) Update CHANGELOG for 0.34.0 release

---

CHANGELOG.md

(maint) Update changelog for 0.37.0 release.

---

CHANGELOG.md
lib/vanagon/platform/defaults/osx-13-arm64.rb

(PA-5329) Add macOS 13 (ARM) platform definition

---

CHANGELOG.md
lib/vanagon/platform/defaults/osx-13-x86_64.rb

Added platform for macos13 intel.

(PA-5326) Added platform for macos13-x86_64

---

CHANGELOG.md

(maint) Preparing for 0.38.0 release

---

CHANGELOG.md

(maint) Prep for 0.39.0 release

---

CHANGELOG.md

(maint) prep for 0.39.1 release

---

CHANGELOG.md
CODEOWNERS

(maint) 0.39.2 release prep

---

CHANGELOG.md
lib/vanagon/platform/defaults/debian-11-aarch64.rb

(PA-5328) Add Debian 11 (ARM) platform definition to vanagon

---

CHANGELOG.md

(maint) 0.39.3 release prep

---

lib/vanagon/platform/defaults/amazon-2023-aarch64.rb
lib/vanagon/platform/defaults/amazon-2023-x86_64.rb
lib/vanagon/platform/dsl.rb

Added amazon-linux-2023 platform in Vanagon

(VANAGON-231) : Added amazon linux 2023 platform for intel & arm

---

CHANGELOG.md

(maint) Release prep for version 0.41.0

---

CHANGELOG.md

(maint) Prep for 0.43.0 release

---

CHANGELOG.md
lib/vanagon/platform/defaults/osx-14-arm64.rb

Added macos14 ARM platform definition to vanagon

(vanagon-237) Added macos14 ARM platform definition to vanagon

---

CHANGELOG.md
lib/vanagon/platform/defaults/fedora-38-x86_64.rb

Added notable changes to CHANGELOG.md file too

(vanagon-228) Add fedora38 x86_64

---

CHANGELOG.md
lib/vanagon/platform/defaults/redhatfips-9-x86_64.rb

- Add Redhat-9 FIPS platform definition to vanagon

RE-16102: add platform support for redhatfips-9

---

CHANGELOG.md

(maint) Prep for 0.45.0 release

---

CHANGELOG.md

(maint) Prep for 0.47.0 release

---

CHANGELOG.md
lib/vanagon/platform/defaults/fedora-40-x86_64.rb

(PA-6347) Add Fedora-40 platform definition to vanagon

---

CHANGELOG.md

(maint)  Prep for 0.48.0 release

---

CHANGELOG.md

(maint) Prep for 0.49.0 release

---

CHANGELOG.md
lib/vanagon/platform/defaults/amazon-7-aarch64.rb

(PA-6262) Change cmake to cmake3 form amazon linux 2 arm

---

CHANGELOG.md

(0.51.0-prep) Prep for 0.51.0 release

---

CHANGELOG.md

(maint) 0.52.0 release prep

---

CHANGELOG.md

- The error was introduced in https://github.com/puppetlabs/vanagon/pull/860

(VANAGON-257) Fix changelog for windowsfips flag addition
